docker-library/docs

php/content.md
Let people know there's a script so cool.
=> Add description for `docker-php-ext-install`

buildpack-deps/content.md
See https://github.com/docker-library/buildpack-deps/pull/15
=> Add some documentation about where the line between the new variants of buildpack-deps is

wordpress/README.md, wordpress/content.md
This goes with https://github.com/docker-library/wordpress/pull/55
=> Add documentation for WORDPRESS_DB_HOST

php/README.md, php/content.md
The configuration File Path is not /usr/local/bin but /usr/local/etc/php
=> Update configuration File (php.ini) Path

node/content.md
npm merged https://www.npmjs.org/ into https:/www.npmjs.com/ a month or so ago. Docs are now at https://docs.npmjs.com/ (instead of https://www.npmjs.org/doc/)
=> Fixed broken links to npm doc

centos/README.md, centos/content.md
separates rolling builds and minor tags for better clarity. 
Added documentation about the `nodocs` yum option for users reporting missing files after installing packages. 
Fixes https://github.com/docker-library/official-images/issues/478
=> update to centos documentation 

websphere-liberty/license.md
https://github.com/docker-library/official-images/pull/487 adds a tag for an image for the WebSphere Liberty Beta and this PR updates the license information for the repo to reference the beta license.
=> Add reference to beta license

Dockerfile
Since we have a monkey patch on `Mojo::UserAgent::CookieJar` in push.pl (which broke recently), we need to specify a Mojolicious version.  And we should use an official image directly to show how easy it is.
Also, swap to entrypoint to make it easier to run.
=> Use official image for push script and specify mojo version

Dockerfile
Turns out BackPAN doesn't have SSL, so we can't have fully secure `cpanm` _and_ have old versions of our dependencies. :cry:
=> Fix downloading older Mojolicious version

odoo/README.md, odoo/content.md
Hi,
We did an update of the doc:
- How to run Odoo with a custom configuration by specifying the arguments inline or using the configuration file
- How to mount custom addons within the container
- Fix the path to filestore
This branch has been rebased to master.
Regards,
=> Odoo - Custom configuration and mounted addons

jetty/README.md, jetty/content.md
This goes along with docker-library/official-images#547. I'll update this PR with the latest refs and amend once the other PR is merged.
=> Document changes to allow Jetty to run --read-only

wordpress/README.md, wordpress/content.md
Based on the discussion in docker-library/wordpress#68 the process to add php-extensions was added. Focus is to make it as easy as possible for the user of the image to create and maintain its own extended image based on docker-library/wordpress.
Not sure whether it makes sense to restrict this description to the wordpress image. Maybe it makes sense to at least partially add the description to all images in docker-library.
However, this should be done once we agree on the documentation for wordpress.
=> Documentation how to add extensions

mysql/content.md
Document that custom config files in /etc/mysql/conf.d must end in .cnf. Otherwise, MySQL will ignore the files.
In particular, the /etc/mysql/my.cnf file inside of the container has the following lines:
```
#
!includedir /etc/mysql/conf.d/
```
=> MySQL custom config files must end in .cnf

java/content.md
It may need a little more wordsmithing, but hopefully this will help users understand the choice to not package Oracle Java.
=> Add info about Oracle Java

iojs/content.md
This PR removes the incorrect double dash from `-it` in one code snippet in the iojs README.
=> Remove extra dash from `-it` in example code

Dockerfile, push.pl
```console
$ ./push.sh ...
diff --git a/tmp/XfqXvwAiit.md b/wordpress/README.md
index df290e6..ad31c26 100644
--- a/tmp/XfqXvwAiit.md
+++ b/wordpress/README.md
@@ -69,7 +69,7 @@ The following Docker Hub features can help with the task of keeping your depende
-This image is officially supported on Docker version 1.5.0.
+This image is officially supported on Docker version 1.6.0.
Support for older versions (down to 1.0) is provided on a best-effort basis.
1> yes
2> vimdiff
3> no
Apply changes? [1]: 
updating wordpress
```
=> Reorganize "push.pl" to put the "vimdiff" logic in one place for cool dispatch-conf-alike behavior

elasticsearch/README.md, elasticsearch/content.md
As I was reading the [Docker Compose overview](https://docs.docker.com/compose/), it wasn't immediately clear how the Python app knew which port to use for redis. Once I started reading the [public image for redis](https://registry.hub.docker.com/_/redis/), it became super clear.
> This image includes `EXPOSE 6379` (the redis port), so standard container linking will make it automatically available to the linked containers (as the following examples illustrate).
After finding [the elasticsearch image also exports default ports](https://github.com/docker-library/elasticsearch/blob/master/1.5/Dockerfile#L30), I thought this added documentation would be helpful.
=> elasticsearch: document exposed ports

wordpress/content.md
As added in https://github.com/docker-library/docs/pull/219 for `drupal`.
=> Point out that wordpress's own Dockerfile has an "extra libraries" example

mongo/content.md
fixes #236
fixes https://github.com/docker-library/mongo/issues/30
=> Add mongo docs for volume, storageEngine, mmap on vboxsf

haproxy/README.md, haproxy/content.md
being new to docker and haproxy, it took me quite a while to figure out why things just did not work. the issue was also reported in the haproxy repository: https://github.com/docker-library/haproxy/issues/1
=> add note about daemon mode

jruby/README.md, jruby/content.md, ruby/README.md, ruby/content.md
The jruby and ruby documentation had a typo in the onbuild tag details. This pull-request fixes them.
=> Small docs fix, onbuid to onbuild

redis/README.md, redis/content.md
Added "redis-server" into the example run command to use a custom config
file at launch
https://github.com/docker-library/official-images/issues/858
=> corrected example run command in redis README

redis/content.md
See also https://github.com/docker-library/redis/pull/28, https://github.com/docker-library/official-images/pull/897, and http://redis.io/topics/memory-optimization#using-32-bit-instances.
=> Update variant.sh with a bit more flexibility (so we can have "variant override" files per-image)

postgres/content.md
Provide info on getting past Postgres `initdb`'s grumpiness with fs mounts. Related to this [PR](https://github.com/docker-library/postgres/pull/72).
=> Explain `PGDATA` env variable, which is useful when data volume is fs mount.

postgres/content.md
Documentation change for https://github.com/docker-library/postgres/pull/75.
=> Add documentation for new postgres initdb logic

rabbitmq/README.md, rabbitmq/content.md
Include instructions on README showing how to use RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS environmental variables
fixes: https://github.com/docker-library/rabbitmq/issues/34
=> RabbitMQ: Add instructions on how to set default user and password 

websphere-liberty/content.md, websphere-liberty/license.md
Add details of shared class cache usage and note on use of boot2docker ip (as per comment submitted on Docker Hub).
=> Updates to websphere-liberty docs

ros/content.md
docker `network` is still an experimental feature and is not yet in v1.8 stable release :disappointed: 
I stand corrected, see: https://github.com/docker/docker/issues/14083#issuecomment-130349799
Sorry about the noise @tianon :pray:
=> Small correction to ROS docs

php/content.md
Apparently COPY will expect a full target path nowadays:
```
Step 0 : FROM php:5.6-apache
---> 86db229ab259
Step 1 : COPY config/php.ini /usr/local/etc/php
stat /var/lib/docker/devicemapper/mnt/cb571a2599018afc008c08a509d201d4937eed74a22621efa94e3ef32bebc869/rootfs/usr/local/etc/php/php.ini: not a directory
```
=> [php] Fix php.ini COPY Documentation

odoo/content.md
moved from https://github.com/docker-library/docs/pull/324
=> Fixed typo in db-filter config

jetty/content.md
Since @gregw will be unavailable to make updates to #327 for a few days, I'm opening a new PR with his changes plus the tweaks necessary to appease `markdownfmt` (along with a minor change to the example `Dockerfile` for adding new Jetty modules).
This PR goes along with https://github.com/docker-library/official-images/pull/1005 (which should be mergeable with passing tests if https://github.com/docker-library/official-images/pull/1010 is applied).
Closes #327.
=> Update Jetty docs for CMD changes

mariadb/content.md, mysql/content.md, percona/content.md
Here is a diff to show the changes from MySQL to MariaDB (and Percona in the second diff)
```diff
diff --git a/mysql/content.md b/mariadb/content.md
index 13fa72b..f9d8112 100644
--- a/mysql/content.md
+++ b/mariadb/content.md
@@ -1,8 +1,10 @@
-# What is MySQL?
+# What is MariaDB?
-MySQL is the world's most popular open source database. With its proven performance, reliability and ease-of-use, MySQL has become the leading database choice for web-based applications, covering the entire range from personal projects and websites, via e-commerce and information services, all the way to high profile web properties including Facebook, Twitter, YouTube, Yahoo! and many more.
+MariaDB is a community-developed fork of the MySQL relational database management system intended to remain free under …
```
=> Sync the MySQL docs to MariaDB and Percona

jetty/content.md
Jetty has had HTTP/2 support since Jetty 9.3.2 or earlier, but the changes in Jetty 9.3.3 (cf. docker-library/official-images#1088) make it easy to configure and use in the `jetty` image as an HTTP/2 server.
=> Jetty: Update docs for HTTP/2 support

sentry/content.md
If the database is not linked, the workers do not find the tables.
=> celery workers also need the database connection

.template-helpers/docker-versions.md
Also, add a link to the Docker docs for installation.
=> Move the theoretical best-effort support line from Docker 1.0 up to Docker 1.6

rails/content.md
Fixes https://github.com/docker-library/official-images/issues/1104
=> Rails, no need to bundle install in the throw-away container

python/variant-onbuild.md
Give more details on how the onbuild variant of Python is different for people who are more familiar with Python than with Docker. More details in PR #360.
=> Explain the python:onbuild variant.

sentry/content.md
Celery workers need to be linked to postgres; celery beat doesn't.
cc @mattrobenolt
=> Link postgres as needed in sentry docs.

sentry/content.md
This doesn't make sense and will never work.
See discussion on https://github.com/docker-library/docs/pull/376
/cc @yosifkit
=> sentry: remove reference to vanilla celery image

cassandra/content.md
Fixed "the vElue" -> "the value"
=> fix a typo in cassandra/content.md

cassandra/content.md
Hi,
I am using this image to setup a spark+cassandra cluster and I was wondering if we could use the docker run --link option to link new node to the first one instead of docker inspect command value pass to an environnement variable.
With this change, adding a node to the cluster is simpler, isn't it ?
docker run --name some-cassandra2 -d --link some-cassandra:cassandra cassandra:tag
WDYT? sorry if I am wrong, I am neither a docker expert, nor a C* one ;-)
cf: https://github.com/docker-library/cassandra/pull/21 and https://github.com/docker-library/docs/pull/303
=> document linking a new Cassandra node to the first one

php/content.md
Thanks to @wsilva! Without explicit port forwarding, the command did not work.
=> Fix instruction for without dockerfile example

.template-helpers/variant-alpine.md
As discussed in https://github.com/docker-library/golang/pull/69 -- try to explain that common tooling which is not strictly needed is often not included in Alpine images. (E.g. git in golang)
Closes docker-library/golang#69
=> variant-alpine: explain often missing tooling

ubuntu-debootstrap/deprecated.md, ubuntu-upstart/deprecated.md, update.sh
Visual difference between `# a` and `# **a**` in current Docker Hub rendering:
=> Add capability for a simple deprecation notice, and add one for ubuntu-debootstrap and ubuntu-upstart

golang/content.md
Hello!
If a Makefile contains shell command, we should use a shell to launch make process.
=> Some commands (e.g pwd) need bash

oraclelinux/README.md, oraclelinux/docker-versions.md
Thanks to @tianon's tips in #404 (which is a great issue number), I've added `docker-versions.md` and rebuilt `README.md` using `update.sh`.
The new text provides more accurate support information for both Oracle support customers and users without a paid support subscription.
=> Updated the Oracle Linux documentation

golang/content.md
Fixes docker-library/golang#41
=> Add a note about how to remove the spurious stderr blurb in golang:onbuild

.template-helpers/generate-dockerfile-links-partial.sh
-	[`1.4.3`, `1.4` (*1.4/Dockerfile*)](https://github.com/docker-library/golang/blob/a4f3927494b48c7bdb6ea6edac8f89818853b45b/1.4/Dockerfile)
-	[`1.4.3-onbuild`, `1.4-onbuild` (*1.4/onbuild/Dockerfile*)](https://github.com/docker-library/golang/blob/3427e88341de17a4d8921b859180a2649e1ab96e/1.4/onbuild/Dockerfile)
-	[`1.4.3-cross`, `1.4-cross` (*1.4/cross/Dockerfile*)](https://github.com/docker-library/golang/blob/3427e88341de17a4d8921b859180a2649e1ab96e/1.4/cross/Dockerfile)
-	[`1.4.3-wheezy`, `1.4-wheezy` (*1.4/wheezy/Dockerfile*)](https://github.com/docker-library/golang/blob/a4f3927494b48c7bdb6ea6edac8f89818853b45b/1.4/wheezy/Dockerfile)
-	[`1.4.3-alpine`, `1.4-alpine` (*1.4/alpine/Dockerfile*)](https://github.com/docker-library/golang/blob/5fc9acac9ae394e055cdc2e80400bf78e360cd2c/1.4/al …
=> Add a link that shows off our image layer sharing

php/content.md
See https://bz.apache.org/bugzilla/show_bug.cgi?id=50669 for additional detail from upstream.
Fixes docker-library/php#64
=> Remove "-it" from Apache invocations of "docker run" (due to SIGWINCH killing Apache, by design)

notary/README-short.txt, notary/content.md, notary/license.md
PR for images here: https://github.com/docker-library/official-images/pull/1423
Signed-off-by: David Lawrence <david.lawrence@docker.com> (github: endophage)
=> Adding notary docs

postgres/content.md
Closes #218 (carry of the change forward into `psql` land)
=> Add "psql" initdb example to postgres

mariadb/content.md, mysql/content.md, percona/content.md
Needs https://github.com/docker-library/mysql/pull/147, https://github.com/docker-library/percona/pull/15, https://github.com/docker-library/mariadb/pull/45 for end user clarity when using `--help`.
```console
$ # new:
$ docker run -it --rm maridb --help
mysqld  Ver 10.1.11-MariaDB-1~jessie for debian-linux-gnu on x86_64 (mariadb.org binary distribution)
Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.
Starts the MariaDB database server.
Usage: mysqld [OPTIONS]
For more help options (several pages), use mysqld --verbose --help.
$ # old, one of the password options is required to get anywhere
$ docker run -it --rm -e MYSQL_ALLOW_EMPTY_PASSWORD=1 mariadb --help
...# tons of output creating the initial database
Database initialized
MySQL init process in progress...
mysqld …
```
=> Add encoding hints for mysql, mariadb, and percona

php-zendserver/content.md
Missing line breaks caused heading and paragraphs to bleed together.
Missing line breaks caused lists to become run-on paragraphs.
Space-hyphen-space replaced with unicode dash in cases when a dash would normally be used in English
Signed off by Devvyn Murphy
=> correct formatting errors in php-zendserver README.md (content.md)

mongo-express/content.md
This removes a reference to knickers/mongo-express I had missed in an example, and changes it to the official mongo-express.
=> Remove reference to knickers/mongo-express

mariadb/content.md, mysql/content.md, percona/content.md
Closes #375
If this wording is amenable, I'm happy to replicate it out to `mariadb` and `percona`'s `content.md` files as well.
=> Note an easy way to run "mysqldump"

swarm/README.md, swarm/license.md
The license links in the README and license markdown files went 404.  I linked them to the code section (seemed natural compared to the docs' license).
=> Fix license link

chronograf/content.md, influxdb/content.md, kapacitor/content.md, telegraf/content.md
Fixing some small inconsistencies between them so now the documentation
is more uniform and all of the commands work correctly and are formatted
the same.
=> Updating the TICK stack documentation

registry/github-repo
This is still pointing to the old `docker/registry` repo.
@RichardScothern, is `docker/distribution-library-image` the correct repo for users to file issues that they have with the registry image or would `https://github.com/docker/distribution` be better?
=> Update registry repo github url

alpine/content.md
This way there's no need to delete `/var/cache/apk`, leading to a cleaner Dockerfile.
Supported since alpine 3.3, hence the change from 3.1.
Let me know if there's something else to be done.
Related: https://github.com/gliderlabs/docker-alpine/blob/f93486d/docs/usage.md#disabling-cache
=> Update apk install pattern to use `--no-cache'

notary/content.md
the old links coughed up 404
Signed-off-by: Andrew Hsu <andrewhsu@acm.org>
=> fix links to notary config docs

odoo/content.md
The odoo docker image is based on debian:jessie, which only has
postgresql-client-9.4, while the official postgres docker
has 9.5 server. This causes a version mismatch and errors when using the
postgres command-line tools, such as `pg_dump`.
Thanks!
Fixes odoo/odoo#12275
Fixes odoo/docker#49
Fixes odoo/docker#54
Fixes odoo/docker#59
=> Odoo: force postgres version in docker command line

chronograf/github-repo, influxdb/content.md, influxdb/github-repo, kapacitor/github-repo, telegraf/github-repo
Removed the `docker exec` example since it doesn't appear to work because of
docker/docker#8755 and added a clarification to how to use the admin interface.
=> Switch the github-repo for influxdb, kapacitor, and telegraf

rethinkdb/github-repo
The move to the official RethinkDB organization wasn't previously reflected in the docs.
=> Fix rethinkdb/rethinkdb-dockerfiles#31

ros/content.md
Changed the docker-compose part to reflect the new version 2 of docker-compose. Some changes like [docker-compose "--x-networking" up -d] were not running at all, while others would soon be deprecated.
=> ROS: Update for version 2 of docker-compose

rails/deprecated.md
Given what it is (just a framework), and looking through https://github.com/search?l=dockerfile&q=%22FROM+rails%22&type=Code, I think it's time we finally cut the cord.
=> Officially deprecate "rails"

couchbase/README-short.txt, couchbase/content.md, couchbase/license.md
This change passes markdownfmt -d *except* for three `code` elements that contain nested backticks. I tried many variations and could not find one that markdownfmt liked. In at least one case, markdownfmt suggested a change, but when I made that change it rejected it in a different way. So I eventually gave up. The three blocks in question seem to render OK on GitHub at least. Hopefully this is either acceptable as-is or you can tell me what markdown incantation to use.
=> Updated with more relevant quickstart information

sentry/README.md, sentry/variant-onbuild.md
Hi,
I'm guessing there's a fair chance that the venn diagram of sentry users and docker users doesn't have too much overlap. I've updated the onbuild image documentation to help people get started with a little more information.
I hope you find my additions to the readme helpful.
Thanks.
=> Update onbuild instructions

wordpress/docker-compose.yml
Closes #532
Made possible by https://github.com/docker-library/wordpress/pull/144.
=> Convert wordpress example "docker-compose.yml" to version 2

spiped/README-short.txt, spiped/content.md, spiped/github-repo, spiped/license.md
Closes #564 (carried)
Just moved the `update.sh` bit over to `spiped/github-repo`.
cc @TimWolla :+1:
=> Add spiped docs

postgres/content.md
There does not seem to be any difference in this particular page, but I thought it might make sense to link to the latest stable docs anyway.
=> [postgres] Update link to point to latest stable (9.5) docs

mysql/content.md
Update content.md: Explain execution order of initdb scripts
This addresses https://github.com/docker-library/mysql/issues/195
=> Update content.md: execution order of initdb scripts

.template-helpers/generate-dockerfile-links-partial.tmpl
It would appear that CenturyLinkLabs has no interest in updating ImageLayers for v2 images, and thus no longer loads our images. :cry:
=> Remove broken imagelayers badges

crate/content.md
Updated the docs to remove deprecated bits of documentation. ES 2.X disallows having custom configuration paths, and so do we.
Cheers, Claus
=> Crate: Updated docs to reflect config file changes

ghost/README.md, ghost/content.md
Closes #663 (carried/squashed commits in e2f651d)
cc @pascalandy
`*/README.md` are generated from `*/content.md` :+1:
=> Add info to Ghost about finding Node Version

README.md
Also removed from the private repo behind docs.docker.com (though not published yet at the time of writing).
=> Remove unused email alias.

django/deprecated.md
See https://github.com/docker-library/docs/pull/503 for the justification of the deprecation of `rails`, which all applies here as well.
Closes #189
Closes https://github.com/docker-library/official-images/issues/589
=> Officially deprecate "django"

neo4j/README.md, neo4j/content.md
Both will be 404 soon (if not already).
=> Fix links to Neo4j documentation

hipache/deprecated.md
cc @dmp42 @samalba -- any objections to deprecating the `hipache` official image?
We don't plan to remove the artifacts (in case folks are still using them), but it does seem prudent to let our users know the status of the project.
If there aren't objections to the deprecation, then I'd appreciate suggestions for improvement on the wording of the deprecation notice, especially whether the "potentially similar solutions" list is even in the right ballpark. :innocent: :heart:
=> Deprecate "hipache" due to upstream inactivity

iojs/deprecated.md
Since Node.js 4+, io.js has been merged back with the Node.js project, but our documentation has yet to reflect that fact. :+1:
cc @hmalphettes @retrohacker @Starefossen @pesho @chorrell (tagging a few contributors to both `library/iojs` and `library/node` both FYI and for review :heart:)
=> Deprecate the "iojs" image

debian/content.md
Ref https://github.com/docker-library/official-images/pull/2275
Ref https://github.com/tianon/docker-brew-debian/issues/37
So long `httpredir`, and thanks for all the fish. :heart: :tropical_fish: :fish: :blowfish: :fishing_pole_and_fish: :fish_cake: :green_heart:
=> Update the Debian notes to talk about deb.debian.org instead of httpredir.debian.org

redis/content.md
The link to "docs.docker volumes" is 404. Updated with what I think is the equivalent page.
Before:
http://docs.docker.com/userguide/dockervolumes/
After:
https://docs.docker.com/engine/tutorials/dockervolumes/
=> Redis: Update docker volumes documentation URL

debian/content.md
This is the companion to https://github.com/docker-library/official-images/pull/2318 :+1:
=> Add some notes about the new "<suite>-slim" Debian variants and update the existing "dist" note

mongo-express/content.md
This documents the new command line replica-set syntax implemented here: https://github.com/docker-library/official-images/pull/2339
=> Document the new replica set compatibility

influxdb/content.md, kapacitor/content.md
The web interface is deprecated and is now disabled by default. It will
be removed in the future so stop encouraging its use.
=> Update influxdb documentation to remove web interface as a default setting

centos/content.md
https://github.com/docker-library/docs/blob/master/centos/content.md#dockerfile-for-systemd-base-image there is a `\` missing
=> centos add missing \ in content

php/content.md
Similar fix to https://github.com/docker-library/docs/pull/767
=> Fix xcache example and add example of using docker-php-ext-* with an absolute path

consul/content.md
This should close https://github.com/docker-library/docs/pull/611.
=> Adds Google DNS recursor to DNS example.

php/content.md
See https://github.com/docker-library/docs/issues/764#issuecomment-266828154
=> Add an example of installing "redis" and "xdebug" from PECL (PHP 7.1 compatible)

influxdb/content.md
Just correct a minor error about CLI.
Thanks
=> Update doc about an error of CLI command

elasticsearch/content.md
Related to https://github.com/docker-library/elasticsearch/issues/98.
=> Add upstream quote about elastic 5.x vm.max_map_count check

haproxy/content.md
haproxy 1.7 is now stable, so updating the docs to reference it
=> Update haproxy docs to reference version 1.7

registry/README-short.txt, registry/content.md
This removes the Registry v1 content completely -- no v1 tags are supported anymore, and we only need to document what actually is still supported.
Closes https://github.com/docker-library/official-images/issues/2524
cc @stevvooe @dmcgowan
I left in the bits about "Docker Trusted Registry" at the end, but I was kind of wondering if those ought to be updated to talk about the fact that "Docker Trusted Registry" is now part of "Docker Datacenter" (and isn't sold standalone anymore AFAIK; the link we've got redirects to the DDC info) -- thoughts?
=> Update Registry content for v2

elasticsearch/content.md
Change related to docker-library/elasticsearch#153
I'm really not fluent in english so feel free to change the entire wording of this PR :)
=> Explain cluster not supported for elasticsearch

drupal/content.md, drupal/docker-compose.yml
I tested this by using `docker-compose up -d`, going through Drupal's web-based setup process to get Drupal fully configured and operational, then used `docker-compose up -d --force-recreate` to force both containers to be re-created (which works very hard to keep the volumes), and verified that my site was still configured and working properly.
Closes https://github.com/docker-library/drupal/issues/3
=> Add some notes about volumes in Drupal, especially updating "docker-compose.yml"

postgres/content.md
This is some initial documentation for the caveats noted in https://github.com/docker-library/postgres/pull/253.
=> Add some notes about the caveats for "arbitrary user" support in postgres

influxdb/content.md
In the command-line example, the port 2003 is not exposed when the Graphite support is enabled.
=> Expose port 2003 if Graphite support is enabled

gazebo/content.md
Curl may not be installed by default in newer ubuntu images, so for the tutorial, gazebo8 image is missing curl: https://github.com/osrf/docker_images/issues/46
Also updating token Dockerfile
=> [Gazebo] Updating docs about curl

composer/content.md
describe how to overcome non-existant user errors that git might throw
when combining the custom user and private repositories scenarios
=> expand composer documentation

spiped/content.md
Add Docker's `--init` flag to example invocations of spiped.
This removes the warning introduced by the patch at: https://github.com/TimWolla/docker-spiped/blob/master/1.5/Dockerfile#L14-L16
My intent is to remove the patch in the future and coordinate with upstream whether it should remain in the upcoming spiped 1.6 version or whether it should be completely removed.
=> Add --init flag to spiped examples

ibmjava/content.md
Reverts docker-library/docs#827. Due to an issue with the latest JDK (1.8.0_sr4) this change needs to be reverted to the previous level (1.8.0_sr3fp22).
=> Revert "Bump Java version to 1.8.0_sr4 (8.0-4.0)."

ibmjava/content.md, ibmjava/license.md
Add license info for IBM Java 9 EA.
Update Java 9 Beta Community URL.
=> Bump IBM Java version to 1.8.0_sr4fp1 (8.0-4.1).

znc/README-short.txt, znc/content.md, znc/github-repo, znc/license.md, znc/variant-slim.md, znc/variant-small.md
For https://github.com/docker-library/official-images/pull/2617
=> Add docs for ZNC image

postgres/content.md
This additional note was suggested by @shane-axiom over in https://github.com/docker-library/postgres/pull/253#issuecomment-282900633. :heart:
=> Add an explicit note about initdb scripts being run as the "postgres" user now

.template-helpers/template.md, push.pl
```console
...
no change to debian; skipping
$ git status
On branch master
Your branch is up-to-date with 'docker-library/master'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   .template-helpers/template.md
modified:   debian/README.md
modified:   push.pl
no changes added to commit (use "git add" and/or "git commit -a")
$ git diff debian/
diff --git a/debian/README.md b/debian/README.md
index bfe6a76..cfc27ce 100644
--- a/debian/README.md
+++ b/debian/README.md
@@ -1,3 +1,9 @@
+
+
-      [`8.7`, `8`, `jessie`, `latest` (*jessie/Dockerfile*)](https://github.com/tianon/docker-brew-debian/blob/a3d2e76fdd618d1ca1b145c0a2268e828d547ea2/jessie/Dockerfile)
```
=> Add (and later strip) a nice warning at the top of README.md about it being auto-generated

nuxeo/content.md
The `NUXEO_CLID` is often misunderstood.
=> Add pointer to Nuxeo documentation for Docker setup

centos/content.md
https://docs.docker.com/engine/deprecated/#maintainer-in-dockerfile
=> centos remove MAINTAINER

postgres/content.md
The PostgreSQL image sets up trust authentication and may be confusing for folks who are unfamiliar with it. Add a note to explain this.
=> Add details about trust authentication.

nginx/content.md
Nginx images come with two binaries inside (nginx and nginx-debug), but it hasn't been reflected in image information yet, so this small pull request fixes it.
Discussion started in nginxinc/docker-nginx#55
=> Added information about running nginx in debug mode

postgres/content.md
docker-library/postgres#224 and docker-library/official-images#2762 added the POSTGRES_INITDB_XLOGDIR variable. This adds documentation for that variable.
=> Document postgres POSTGRES_INITDB_XLOGDIR variable

rabbitmq/content.md
See also https://github.com/docker-library/rabbitmq/pull/105#issuecomment-292227485 and https://github.com/docker-library/rabbitmq/pull/149.
=> Add a section about RABBITMQ_VM_MEMORY_HIGH_WATERMARK

celery/deprecated.md
See https://github.com/docker-library/celery/issues/12 / https://github.com/docker-library/celery/issues/1#issuecomment-287655769 for more discussion/details (or the content of this PR). :+1:
=> Deprecate Celery

drupal/content.md
We either need to explain that this is maintained by the Docker community or pull the image from docker.  We are getting push back on our side about this.
=> Explain who maintains this image

redmine/content.md
- `REDMINE_DB_MYSQL`, `REDMINE_DB_POSTGRES`, `REDMINE_DB_PORT`, `REDMINE_DB_USERNAME`, `REDMINE_DB_PASSWORD`, `REDMINE_DB_DATABASE`, `REDMINE_DB_ENCODING`, and `REDMINE_PLUGINS_MIGRATE`
Most of these have been around since https://github.com/docker-library/redmine/pull/24 :open_mouth: :disappointed: and one from https://github.com/docker-library/redmine/pull/10.
Fixes https://github.com/docker-library/redmine/issues/69.
=> Add documentation for existing redmine env vars

.template-helpers/stack.md, update.sh, wordpress/content.md, wordpress/stack.yml
Closes #912
Here's an example of what this generates: (and that "Try in PWD" link should actually work!)
Example `stack.yml` for `wordpress`:
```yaml
version: '3.1'
services:
wordpress:
image: wordpress
ports:
- 8080:80
environment:
WORDPRESS_DB_PASSWORD: example
mysql:
image: mysql:5.7
environment:
MYSQL_ROOT_PASSWORD: example
```
[![Try in PWD](https://github.com/play-with-docker/stacks/raw/cff22438cb4195ace27f9b15784bbb497047afa7/assets/images/button.png)](http://play-with-docker.com?stack=https://raw.githubusercontent.com/docker-library/docs/0cb43ce8ad1da073bbc30c6245cdffb433ba51ba/wordpress/stack.yml)
Run `docker stack deploy -c stack.yml wordpress` (or `docker-compose -f stack.yml up`), wait for it to initialize completely, and visit `http://swarm-ip:8080`, `http://localhost:8080` …
=> Convert "wordpress" to use "docker stack deploy" as an initial "stack" foray

.template-helpers/variant-onbuild.md, python/variant-onbuild.md
Closes https://github.com/docker-library/official-images/issues/2076
=> Deprecate onbuild variants (minus sentry:onbuild)

nuxeo/content.md
As Nuxeo image now runs with user `nuxeo`, then it's not possible anymore to run root commands without explicit switching.
=> Add information on how to run command as root in Dockerfile

.template-helpers/generate-dockerfile-links-partial.tmpl
(Displaying architecture information in a clean, simple way per-tag is still definitely a big WIP/unknown.)
=> Use architecture-specific fields in link generation for now

.template-helpers/generate-dockerfile-links-partial.tmpl
See https://github.com/docker-library/official-images/pull/3098 (which was the prerequisite for this work).
Here's the diff this generates for the `python` image:
```diff
diff --git a/python/README.md b/python/README.md
index c23f79f0..410b8525 100644
--- a/python/README.md
+++ b/python/README.md
@@ -22,6 +22,7 @@ WARNING:
-	[`2.7.13-alpine3.6`, `2.7-alpine3.6`, `2-alpine3.6` (*2.7/alpine3.6/Dockerfile*)](https://github.com/docker-library/python/blob/e81758e60c9214db0ab9da54c0e741b2a2d62e31/2.7/alpine3.6/Dockerfile)
-	[`2.7.13-wheezy`, `2.7-wheezy`, `2-wheezy` (*2.7/wheezy/Dockerfile*)](https://github.com/docker-library/python/blob/1ca4a57b20a2f66328e5ef72df866f701c0cd306/2.7/wheezy/Dockerfile)
-	[`2.7.13-onbuild`, `2.7-onbuild`, `2-onbuild` …
```
=> Update Dockerfile links to use the first arch of an entry if amd64 isn't supported (brings back windows-amd64-only entries)

scratch/README.md
There are _several_ comments on the Hub noting this section of the docs, so I figured we should add it to the description directly instead.
=> Add a quote blurb from the upstream docs to the scratch description

.template-helpers/generate-dockerfile-links-partial.tmpl, .template-helpers/variant.sh, update.sh
This uses the combination of us pushing to a namespace + `BASHBREW_ARCH` being set to determine whether we're pushing to an arch-specific page and should thus appropriately filter all content to the current architecture.
Special thanks to https://github.com/docker-library/official-images/pull/3189 and https://github.com/docker-library/go-dockerlibrary/pull/15 for making this easier to implement.
=> Update docs to filter arch-specific content a bit better (variants, supported tags)

nats/content.md
The Windows Docker Images were not working. This release fixes this.
Details can be found [here](https://github.com/nats-io/gnatsd/releases/tag/v1.0.2)
=> [nats] Release v1.0.2

node/content.md, node/license.md
This came up in https://github.com/nodejs/docker-node/issues/243#issuecomment-316411612
=> Update node README.md

perl/content.md
Instead of providing an `onbuild` variant, show to the user how it is
created instead, by example.
See Perl/docker-perl#13 and
docker-library/official-images#2076
=> Add example on how to make an onbuild image for Perl

openjdk/content.md
Relevant links:
https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/
https://bugs.openjdk.java.net/browse/JDK-6515172
https://bugs.openjdk.java.net/browse/JDK-8170888
https://bugs.openjdk.java.net/browse/JDK-8157478
https://github.com/moby/moby/issues/27892
https://github.com/moby/moby/issues/30594
https://superuser.com/a/908870
https://technet.microsoft.com/en-us/library/cc770297%28v=ws.11%29.aspx
=> Add notes about CPU and RAM limits

cassandra/content.md
Current URL (https://cassandra.apache.org/doc/cql3/CQL.html) returns a 404.
URL in this PR (https://cassandra.apache.org/doc/latest/cql/index.html) takes reader to latest version of CQL documentation, currently version 3.
=> Update URL to CQL documentation

mongo/content.md
Fixes https://github.com/docker-library/mongo/issues/197.
=> Add note about WiredTiger being the default storage engine.

mongo/content.md
Closes docker-library/mongo#198
=> Add a note to mongo about "/data/configdb" (and --configsvr)

flink/content.md
Fix typo as reported by @therw in https://github.com/docker-flink/docker-flink/issues/23.
=> [flink] fix typo

.template-helpers/variant.sh, .travis/check-markdownfmt.sh, debian/content.md, debian/variant-slim.md, debian/variant.md
Thanks to @djeikyb for pointing this out over in https://github.com/docker-library/golang/pull/175. :+1:
Here's the full diff of all generated `README.md` files following this change:
```diff
diff --git a/debian/README.md b/debian/README.md
index 2cd5bf96..f455238e 100644
--- a/debian/README.md
+++ b/debian/README.md
@@ -100,14 +100,16 @@ RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/*
ENV LANG en_US.utf8
\```
-## `<suite>-slim` variants
-
-These tags are an experiment in providing a slimmer base (removing some extra files that are normally not necessary within containers, such as man pages and documentation), and are definitely subject to change.
-
-See the `debuerreotype-slimify` script (`debuerreotype` linked below) for more details about what gets …
=> Fix variant detection for tags like "1.8-onbuild"

openjdk/variant-slim.md
Docs for https://github.com/docker-library/official-images/pull/3424 and https://github.com/docker-library/openjdk/pull/143.
```diff
diff --git a/../.template-helpers/variant-slim.md b/variant-slim.md
index 8c9dd03a..9b10ed93 100644
--- a/../.template-helpers/variant-slim.md
+++ b/variant-slim.md
@@ -1,3 +1,3 @@
-This image does not contain the common packages contained in the default tag and only contains the minimal packages needed to run `%%IMAGE%%`. Unless you are working in an environment where *only* the `%%IMAGE%%` image will be deployed and you have space constraints, we highly recommend using the default image of this repository.
+This image installs the `headless` package of `%%IMAGE%%` and so does not contain the common packages contained in the default tag and only contains …
```
=> Add custom description for slim openjdk to point out headless

.template-helpers/generate-dockerfile-links-partial.tmpl
This is based on what we spitballed over in https://github.com/docker-library/go-dockerlibrary/pull/2#issuecomment-277853597 and created an actual `bashbrew cat` format for in https://github.com/docker-library/official-images/issues/2289#issuecomment-279048796. :+1:
=> Add SharedTags information to "Supported tags" listing

kong/README.md, kong/content.md
Remove -it from migration run since it was tripping up a script I was writing. This is not needed because it is not being used interactively here.
=> Update README.md for Kong

httpd/content.md
Add '-p 80:80' to the example without a Dockerfile.
This expose the port 80 so that users can conect to the server through a web client.
=> Add port option in the example without a Dockerfile

telegraf/content.md
That command has apparently not existed since 1.0.
=> Remove reference to -sample-config in the telegraf docs

cassandra/content.md
Fixes https://github.com/docker-library/cassandra/issues/57. Replaces and closes https://github.com/docker-library/cassandra/pull/118.
=> Explicitly mention the need for `CASSANDRA_ENDPOINT_SNITCH` when using DC/RACK variables

wordpress/variant-cli.md
Closes #1023
See https://github.com/docker-library/wordpress/pull/198 for where these were initially added.
This is a simpler alternative to https://github.com/docker-library/docs/pull/1024 (leaving more of the specifics of how one might use this in their own deployments as an exercise for the reader, sticking instead to describing the basics of what the image is and what it requires for use).
=> Add a simple description of the WP-CLI variants

consul/content.md
At least under ``Docker version 17.07.0-ce-rc4``,  running consul for development does not work
without being explicit about ``CONSUL_BIND_INTERFACE``
=> fix running consul for development

rabbitmq/content.md
See https://github.com/docker-library/rabbitmq/pull/156#issuecomment-305346747 and the following discussion (and https://github.com/docker-library/rabbitmq/pull/159).
=> Add some notes in rabbitmq about "RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS"

notary/content.md, notary/license.md
Notary has been accepted in to CNCF and will be moving to `GitHub.com/theupdateframework/notary`. This PR updates the links to point at the new location. I'll circle back here once the move is done to confirm this should be merged, I'm just getting everything staged at this point.
I plan to make the move in the next 48 hours. Most likely some time on Oct 26th. I'm just giving our main known downstreams a chance to respond to the notifications I've sent out.
N.B. the location of the notary official image repo will not be moving in the immediate future, only the location of the primary notary repo.
=> Notary is moving home

.template-helpers/license-common.md, update.sh
This is an attempt to address the additional note by @thresheek over in https://github.com/docker-library/docs/issues/1046#issuecomment-340093102. :+1:
=> Add an additional common boilerplate to the "License" section of all images

websphere-liberty/content.md
Document existing behavior around generation of default Liberty keystore at container startup.
=> Document keystore behavior

postgres/content.md
See https://github.com/docker-library/postgres/pull/374 and https://github.com/docker-library/postgres/issues/372.
=> Adjust "POSTGRES_INITDB_XLOGDIR" to "POSTGRES_INITDB_WALDIR" (with an added note for 9.x)

registry/license.md
fyi @stevvooe @dmp42 @RichardScothern @aaronlehmann @dmcgowan -- this seems like the most appropriate place to link for license information on the Registry image :smile:
For context, it will also have https://github.com/docker-library/docs/blob/a857080d495c0a0a69299733a6343ca12b77ba45/.template-helpers/license-common.md appended to the end.
Refs #1046
=> Add Registry license link

geonetwork/variant-postgres.md
- explain how-to connect to a postgres db, by IP/DNS or container name, using the POSTGRES_DB_HOST environment variable.
- remove reference to legacy docker --link
=> Updated documentation of how-to connect to a postgres database

postgres/content.md
Fixes docker-library/postgres#266 and docker-library/postgres#320.
(also, unrelated whitespace fix)
=> Add notes on how to configure postgres

centos/license.md
cc @jperrin -- does this seem like a sane place to link for this?
For context, it will also have https://github.com/docker-library/docs/blob/a857080d495c0a0a69299733a6343ca12b77ba45/.template-helpers/license-common.md appended to the end.
Refs #1046
=> Add CentOS license link

alpine/license.md
cc @andyshinn @ncopa -- does this seem like a sane place to link for this?
For context, it will also have https://github.com/docker-library/docs/blob/a857080d495c0a0a69299733a6343ca12b77ba45/.template-helpers/license-common.md appended to the end.
Refs #1046
=> Add Alpine license link

.travis/check-required-files.sh
Once we get the last few missing `license.md` files in from #1046, I'll rebase this for a green result and we can party like it's 1969.
Closes #1046
=> Add "license.md" to the list of files Travis verifies

influxdb/content.md, influxdb/variant-data.md, influxdb/variant-meta.md
Adds documentation for the enterprise image variants added here: docker-library/official-images#3821.
=> Add influxdb cluster variant documentation

php/content.md
This blog post (https://tianon.xyz/post/2017/12/26/dockerize-compiled-software.html) is a slightly longer-form explanation of what I outlined over in https://github.com/docker-library/php/issues/75#issuecomment-353673374. :+1:
=> Add a link to "Dockerizing Compiled Software" in the "PHP Core Extensions" section of PHP's docs

mysql/content.md
Closes docker-library/mysql#184
=> Add a pointer to MySQL upstream's "environment variables" docs

php/content.md
This documents the change in https://github.com/docker-library/php/pull/542 with some of the details discussed in https://github.com/docker-library/php/issues/551#issuecomment-354849074.
Closes https://github.com/docker-library/php/issues/551
=> Add a note about blocked Debian PHP packages

convertigo/content.md
In relation to https://github.com/docker-library/official-images/pull/3862
=> Tells to use the `i386/convertigo` image for the Web Connector.

rust/content.md
This is a small tweak to update the example version of Rust used in the docs (which is getting quite old) and fix a small typo.
=> Update Rust examples version to 1.23.0 and fix a typo

golang/content.md
This is a companion to https://github.com/docker-library/golang/pull/205.
=> Remove all reference to deprecated "go-wrapper" script

postgres/content.md
Added a note to explain that POSTGRES_PASSWORD is not the same as PGPASSWORD.  Closes https://github.com/docker-library/postgres/issues/402
=> Elaboration on POSTGRES_PASSWORD

telegraf/content.md
All the links to docs have been broken since the 1.5 release, this PR updates those.
=> telegraf: fix broken links

nats-streaming/content.md
Also add information about `--entrypoint`.
=> [nats-streaming] Fix documentation typos

README.md
It seems that `maintainer.md` is required, so adding it to the README.
=> Add a hint about required maintainer.md

ros/content.md
As per title.
fixes https://github.com/osrf/docker_images/issues/120
=> [ros] [typo] add missing '\' in example Dockerfile

jetty/content.md
The `start.d` files are called `*.ini` (not `*.mod`, as was stated in
the previous documentation)
=> Correct file names in Jetty documentation

jetty/content.md
To run Jetty with particular modules, use the `--module` option; the
previous doc said `--modules`. The Jetty documentation
https://www.eclipse.org/jetty/documentation/9.3.x/startup.html
references the `--module` option many times, but never `--modules`.
=> Correct wrong parameter name in Jetty docs

.template-helpers/git-prefetch.sh, update.sh
In many cases this will be a no-op, but in cases where we don't have the current version fetched, it'll pre-pull the commits from bad-ideas (so we don't fail further down while generating our tag link list).
See https://doi-janky.infosiftr.net/view/flat/job/docs/job/arm32v7/3447/console for a recent example (failing for a few days now).
=> Add "git-prefetch" script to avoid errors like "fatal: Couldn't find remote ref refs/heads/centos-7armhfp"

php/content.md
=> Update "pecl install" lines and add more explanation for why users should use explicit versions when installing from PECL

centos/content.md
Related to https://github.com/CentOS/sig-cloud-instance-images/issues/103
@jperrin Would you consider this a reasonable addition?
=> Provides information around handling kernels with vsyscall disabled

centos/content.md
Related to https://github.com/docker-library/docs/pull/1211 and https://github.com/CentOS/sig-cloud-instance-images/issues/103
@jperrin requested the use of `CentOS 6` instead of `Legacy CentOS`, but one was missed.
=> Updates language for missed "legacy" term

mongo/content.md, mongo/stack.yml
This is mostly based on the MySQL docs.
Some notes:
- I did not use %%STACK%% with a `stack.yml` because the [`adminer`](https://hub.docker.com/_/adminer/) image does not work with MongoDB and I could not quickly find and vet another Mongo admin image.
- I wasn't sure whether this image has the same [problems](https://github.com/docker-library/docs/blob/master/mysql/content.md#environment-variables) around environment variables as MySQL so I skipped mentioning them.
- Example location of mongo config file may not make sense or reflect best practices.
@yosifkit, @tianon
Closes https://github.com/docker-library/mongo/issues/189
=> Update Mongo docs for new configuration features

telegraf/content.md
The telegraf image documentation now includes information about how to
use telegraf to monitor the /proc filesystem of the host and
documentation for how to monitor the docker service from a container.
=> Expanded telegraf documentation for docker specific use cases

drupal/content.md, owncloud/content.md, php/content.md, wordpress/content.md
This is adapated from what's discussed in https://github.com/docker-library/wordpress/pull/249 (and https://github.com/docker-library/wordpress/issues/256, among others).
=> Add a new section in the PHP documentation about running as an arbitrary user

zookeeper/content.md
Hi,
The link for the Dynamic Reconfiguration is not working, I updated it with the latest version available for 3.5.
I didn't push the README because it has another modification when I run `update.sh`:
```diff
-      **Supported architectures**: ([more info](https://github.com/docker-library/official-images#architectures-other-than-amd64))
-       [`amd64`](https://hub.docker.com/r/amd64/zookeeper/), [`arm32v6`](https://hub.docker.com/r/arm32v6/zookeeper/), [`arm64v8`](https://hub.docker.com/r/arm64v8/zookeeper/), [`i386`](https://hub.docker.com/r/i386/zookeeper/), [`ppc64le`](https://hub.docker.com/r/ppc64le/zookeeper/), [`s390x`](https://hub.docker.com/r/s390x/zookeeper/)
+       `amd64`, `arm32v6`, `arm64v8`, `i386`, `ppc64le`, `s390x`
```
=> Zookeeper - Fix link to Dynamic Reconfiguration

postgres/content.md
On `How to extend this image` section, using the script with environment variables given below fails.
File: `docker-entrypoint-initdb.d/init-user-db.sh`
```
#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
CREATE USER docker;
CREATE DATABASE docker;
GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
EOSQL
```
`Environment variables`
```
POSTGRES_USER=testuser
POSTGRES_PASSWORD=testpassword
POSTGRES_DB=mytestdb
```
Error 
```
database "testuser" does not exist
```
The `psql` command is looking for the default database (that is not available). Instead we can pass `--dbname` argument to ask `psql` command to look for newly created database.
File: `docker-entrypoint-initdb.d/init-user-db.sh`
```
#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username …
```
=> psql command with the --dbname params 

postgres/content.md
This updates https://github.com/docker-library/docs/pull/802 to include https://github.com/docker-library/postgres/pull/448. :tada:
=> Update postgres "arbitrary user" notes to reference new nss_wrapper functionality

xwiki/content.md
Namely the support of Docker secrets.
=> Document new features of the XWiki docker image

nginx/content.md
This is necessary for process replacement. (important for signal handling)
=> Update nginx envsubst example to use exec

owncloud/deprecated.md
Upstream maintains their own image (https://owncloud.org/download/#owncloud-server-docker / https://github.com/owncloud-docker/server / https://hub.docker.com/r/owncloud/server/), and it's officially supported and recommended directly by them (so there's really no sense in us duplicating that effort without their involvement).
=> Deprecate our "ownCloud" image

rabbitmq/content.md
Closes https://github.com/docker-library/rabbitmq/issues/138 
Closes https://github.com/docker-library/rabbitmq/issues/264
https://www.rabbitmq.com/relocate.html
Adding this is probably unecessary, users should familiarize themselves with the documentation
Can rabbitmq reload the .conf, or must it be mounted so as to be configured before runtime?
=> Update Rabbitmq docs

nginx/content.md
There's some use cases where it may be necessary/beneficial to run NGINX in read-only mode. I've added some simple instructions to the docs to address these use cases.
=> Add instructions to run nginx in read-only mode

websphere-liberty/content.md, websphere-liberty/license.md
Changes to websphere-liberty docs:
- Updates to the content - related to support for EE8
- Update license version to 18.0.0.2
=> Websphere Liberty: Update doc for EE8 support and license version update

cirros/github-repo
This is a follow-up/companion to https://github.com/docker-library/official-images/pull/4611 (dependent on).
=> Update cirros "github-repo"

php/content.md
Since PHP 7.0 is no longer supported (security only), updated the documentation examples to 7.2.
http://php.net/supported-versions.php
=> Update examples to use PHP 7.2 instead of 7.0

.template-helpers/generate-dockerfile-links-partial.tmpl, .template-helpers/git-prefetch.sh, .template-helpers/variant.sh
This implements https://github.com/docker-library/official-images/pull/4764 in order to resolve https://github.com/docker-library/mongo/issues/296.
I've verified that it has the expected behavior for arm64v8 mongo and postgres, and that doing a full `update.sh` across all images generates no delta. :+1:
=> Implement "archFilter" to fix arch-specific "Shared Tags" lists

mysql/content.md
Closes docker-library/percona#64
This needs to be copied to Percona and MariaDB as well, but there are other changes they need too, so I figured we could start here and then do a separate "resync" PR.
=> Add an "arbitrary user" section to MySQL

ghost/content.md
Several users have run into issues upgrading from Ghost v1 to Ghost v2. Added this section to the Dockerfile to hopefully alleviate such upgrade issues in the future.
=> update ghost readme with 1.x => 2.x migration

postgres/content.md
See https://github.com/docker-library/postgres/pull/440, https://github.com/docker-library/postgres/pull/441, https://github.com/docker-library/postgres/issues/474.
(This is a documentation update for the implementation in docker-library/postgres#440.)
=> Update postgres with note about Unix socket

wordpress/content.md
See https://github.com/docker-library/wordpress/blob/cb50cbaabba8eea67ea6a1f7702a7a1e238f10b9/docker-entrypoint.sh#L147-L151 (where we auto-add the appropriate `HTTP_X_FORWARDED_PROTO` code to `wp-config.php`).
See also https://codex.wordpress.org/Function_Reference/is_ssl#Notes and http://codex.wordpress.org/Administration_Over_SSL#Using_a_Reverse_Proxy.
Closes https://github.com/docker-library/wordpress/issues/331
=> Add a short blurb about TLS + WordPress + NGINX

amazonlinux/content.md
`sudo` is not necessary for the commands listed.
=> Update documentation for amazonlinux usage

bonita/content.md, cassandra/content.md, mariadb/content.md, mongo/content.md, mysql/content.md, percona/content.md, redmine/content.md, teamspeak/content.md
This really isn't our place to document -- this is a generic Docker issue for users of SELinux.
The official upstream documentation on the topic can be found at https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label.
There's also some good information to be found in http://jaormx.github.io/2018/selinux-and-docker-notes/ and https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/.
Closes #991
=> Remove SELinux specific notes

php/content.md
The PHP image will ship with the default development and production
INI files in order to make it easier to securely configure PHP.
See https://github.com/docker-library/php/pull/711 and https://github.com/docker-library/php/issues/692.
=> Add information on PHP configuration

rabbitmq/content.md
`docker_entrypoint.sh` has the ability to set the RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS by reading a file on the container (instead of storing the values in environment variables). This just adds that functionality to the documentation.
=> Documents setting user/pass from file for rabbitmq

rabbitmq/content.md
Closes https://github.com/docker-library/rabbitmq/issues/279
See also https://github.com/docker-library/rabbitmq/pull/280.
=> Add a blurb about sourcing the Erlang cookie from a file

rabbitmq/content.md
I think this will help with issues like https://github.com/docker-library/rabbitmq/issues/278.
=> Adjust rabbitmq configuration recommendation to use a file above the heinous environment variable

amazonlinux/content.md
We wanted a note to help explain why the vulnerability scanning data doesn't match reality due to backported patches to older version numbers.
(ref https://github.com/aws/amazon-linux-docker-images/issues/8)
=> [amazonlinux] Add a note regarding Docker Hub's vulnerability scanner

postgres/content.md
Resolves https://github.com/docker-library/docs/issues/1318
=> Notes on --shm-size for Postgres

telegraf/content.md
The option `access_log on` is invalid and makes nginx create a logfile called `on`.
=> Fixed config sample for Nginx

wordpress/content.md
Relevant to https://github.com/docker-library/wordpress/issues/344 and https://github.com/docker-library/wordpress/issues/341
As mentioned previously in https://github.com/docker-library/wordpress/issues/246#issuecomment-340557707 and https://github.com/docker-library/wordpress/issues/146; mounting the themes/plugins to `/usr/src/wordpress/wp-content/` was advised, however there are issues notably with themes that cause a `Stylesheet is missing.` even when insuring the directory and it's contents are owned by `www-data` and given 777 permissions. It seems to be related to the `tar cf - --one-file-system -C /usr/src/wordpress . | tar xf -` in the entrypoint
`/var/www/html/wp-content/` doesn't have this problem, it only requires read/write/execute for either the user `www-data` or for …
=>  Add how to include pre-installed themes/plugins for WordPress

websphere-liberty/content.md
One of our users suggested the following addition to clarify that all the copied files must be set with the correct permissions.
=> Clarifying the example

cassandra/content.md
Update inspect format to return the IP using the range of network.
This could maybe improve as it will surely failed if multiple network are attached to the container but that still better that the old format that doesn't work anymore.
=> cassandra: Update inspect format

openjdk/content.md
Since Java 11, the `UseCGroupMemoryLimitForHeap` is removed, and enabled by default. See https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE
I've updated the docs to reflect this.
=> Update Memory settings documentation for Java 11

wordpress/stack.yml
Closes https://github.com/docker-library/wordpress/issues/346
The current example works, but only makes sense if you understand the default values the WordPress image applies to these variables, which is obscure and unhelpful, so this updates the example to be very explicit, and to not use the `root` MySQL account anymore (so it's a safer example too).
=> Update WordPress stack to use more environment variables so it's a better example

php/content.md, php/variant-apache.md, php/variant-cli.md, php/variant-fpm.md, php/variant.md
This will hopefully help clarify some of the image variants and should remove things like the Apache documentation from arm32v6/php (where the image doesn't exist so the documentation doesn't apply).
Closes https://github.com/docker-library/php/issues/741
Refs https://github.com/docker-library/wordpress/issues/346#issuecomment-439700124
=> Adjust PHP documentation organization, especially to utilize "variants" template functionality

traefik/README-short.txt, traefik/content.md, traefik/maintainer.md
Hey!
Here is a small PR that fixes the Traefik spelling (replaces the old deprecated `Træfɪk` by the simpler `Traefik`).
Cheers
=> Fix Traefik spelling

rust/content.md
Using `cargo install` to install the binaries for the package in current working directory is no longer supported, use `cargo install --path .` instead.
Also updated image version in the example to the current one.
=> Update cargo install command

nats/content.md
Details can be found [here](https://github.com/nats-io/gnatsd/releases/tag/v1.4.0)
=> [nats] Release v1.4.0

rabbitmq/content.md
Excellent idea (and excellent summary), @michaelklishin. :heart:
Do you think this covers it sufficiently?  (I didn't feel like it would be terribly useful to copy your post verbatim when it includes additional context if I link to it.)
Closes https://github.com/docker-library/rabbitmq/pull/174
=> Add a blurb explicitly pointing out why RabbitMQ doesn't come with a default HEALTHCHECK

nextcloud/content.md
MariaDB should be setup with the right transaction isolation level and binlog format.
More information is available in the [nextcloud server documentation](https://docs.nextcloud.com/server/14/admin_manual/configuration_database/linux_database_configuration.html#configuring-a-mysql-or-mariadb-database).
Also see [Pull Request 581](https://github.com/nextcloud/docker/pull/581) of the nextcloud docker image.
=> Update nextcloud content.md with mariadb command

mongo/content.md
Closes https://github.com/docker-library/mongo/issues/311
Any suggestions to including a streamlined method of recalculating WiredTiger's formula to use the container's cgroup value `/sys/fs/cgroup/memory/memory.limit_in_bytes` instead of the host's total memory?
=> Add wiredTigerCacheSizeGB info to Mongo docs

mongo/content.md
See the later comments on https://github.com/docker-library/mongo/issues/174 and https://github.com/docker-library/mongo/issues/329 for the discussion which has prompted this expanded clarification.
=> Update Mongo's authentication documentation to be much more explicit and link to more upstream resources

mediawiki/stack.yml
https://devops.stackexchange.com/questions/537/why-is-one-not-allowed-to-use-a-boolean-in-a-docker-compose-yml
Fixes #1406
=> fix(#1406): set Mediawiki MYSQL_RANDOM_ROOT_PASSWORD boolean to a string

docker/content.md
Thanks to @jhoblitt for pointing these out over in https://github.com/docker-library/docker/pull/153 :+1: :heart:
=> Update a few Docker-in-Docker bits

openjdk/variant-oracle.md, openjdk/variant-slim.md
Following a discussion with @tianon, we thought it would be a good idea to improve the OpenJDK image documentation to make it very clear the official image is still available under the GPLv2+CE license.
=> Update openjdk docs

websphere-liberty/content.md
Removing the samples that use a volume to bind an application to WebSphere Liberty, since our best practice guidance is to build a new application image.
=> Clarify WebSphere Liberty Spring usage

adoptopenjdk/README-short.txt, adoptopenjdk/content.md, adoptopenjdk/get-help.md, adoptopenjdk/github-repo, adoptopenjdk/issues.md, adoptopenjdk/license.md, adoptopenjdk/maintainer.md
Adding docs for official images [PR 5710](https://github.com/docker-library/official-images/pull/5710).
=> Add OpenJDK + HotSpot and OpenJDK + Eclipse OpenJ9 images from AdoptOpenJDK.

ros/content.md
The link to the official Docker documentation of the `docker run` command was broken. Also, I took the liberty to update it so that it points specifically to the section about the `--device` option.
=> Fix broken link to Docker documentation (--device)

.template-helpers/generate-dockerfile-links-partial.tmpl
For context, this was added initially because the previous rendering of Markdown on the Hub was such that code in a link would render without underline and barely noticeable blue color (and no hover behavior either besides the normal cursor change), so it wasn't clear it was even a link without additional non-code text. Now that that has been corrected/adjusted, I think it's totally reasonable to remove those (since they're included in the link already).
For reference/comparison, this takes the `open-liberty` readme from ~39k characters down to ~33k characters.
See https://github.com/docker-library/official-images/issues/6030 for discussion.
=> Remove "Dockerfile path" from tags listing

rabbitmq/content.md
HiPE is disabled in latest RabbitMQ image.
More information: https://github.com/docker-library/rabbitmq/issues/342
=> Add deprecation notice about HiPE for RabbitMQ image

.template-helpers/template.md
This really hasn't been horribly relevant for a long time (it was more relevant back when Docker was more frequently making breaking changes to things like image format and those have all been very calm for years now).
=> Remove "Supported Docker versions" quick reference bit

rethinkdb/deprecated.md
This is as discussed in https://github.com/rethinkdb/rethinkdb-dockerfiles/issues/44#issuecomment-503769612 -- I want to be clear that this is intended as a temporary measure, and I do hope to see `rethinkdb` image updates resume in the future! :heart:
=> Deprecate RethinkDB

push.pl, push.sh
Instead of cutting off the end of the image documentation, this change makes the code prefer to trim the entire "Supported tags" list, which for all our images which currently go over the limit brings them down enough to be within.  The note about where to get the full `README.md` file (with the "Supported tags" list intact) still stands, although could maybe do with some better styling and/or wording to make it more obvious (TBD).
I also verified that this change does the right thing in the fallback case by making the `postgres` image description intentionally extra long and verified that it simply trims the description content as before (since taking off the tags doesn't make the description short enough to be under the limit in that case).
Refs …
=> Adjust long-description trimming to prefer trimming tag listing

opensuse/deprecated.md
I believe this is the final step before removing the remaining tags for https://github.com/docker-library/official-images/issues/5371.
@Vogtinator is this accurate?  Should we update this line instead, or is the catch-all of the text above it and the `opensuse/archive` text at the end sufficient?
=> Update opensuse deprecation now that 42.3 is EOL

websphere-liberty/content.md
Fix the image description so the ``` characters do not appear.
=> Fix markdown characters appearing in description

ghost/content.md
Adding this environment variable fixes wrong port on the links when using custom port and connecting to http://localhost:3001 
User experience for first time users is important.
=> ghost: fix example to improve UX for first time users

docker/content.md
This is the companion to https://github.com/docker-library/docker/pull/166. :+1:
=> Revamp "docker" image docs, especially for TLS

docker/content.md
See https://github.com/docker-library/docker/pull/174.
Given that this is an experimental feature, I think it's reasonable to link to the PR itself as documentation (I've marked as "resolved" several distracting discussions there so the discussion and examples are easy to follow).
=> Add a short blurb linking to the "dind-rootless" PR

perl/content.md
Describe how Perl behaves when being run as PID 1 under containers,
particularly on receiving SIGTERM/SIGINT, showing example for explicit
signal handling.
Ref Perl/docker-perl#44
=> perl: Document PID 1 signal handling behavior

geonetwork/content.md
As a workaround to https://github.com/docker/hub-feedback/issues/1849
remove `<` and `>` characters from the example command.
=> Fixes problems with html-like words in GeoNetwork docs

wordpress/stack.yml
Closes https://github.com/docker-library/wordpress/issues/404
=> Add explicit volumes to WordPress stack example

.template-helpers/generate-dockerfile-links-partial.tmpl
> # Supported tags and respective `Dockerfile` links
>
> ## Simple Tags
>
> ...
>
> ## Shared Tags
>
> ...
>
> (See also ["What's the difference between 'Shared' and 'Simple' tags?" in the FAQ](https://github.com/docker-library/faq#whats-the-difference-between-shared-and-simple-tags).)
Refs https://github.com/docker-library/official-images/issues/6282, https://github.com/docker-library/docs/issues/1572#issuecomment-531366628
=> Add a link to our FAQ entry about Shared Tags when we have them

.template-helpers/generate-dockerfile-links-partial.sh
This is to handle explicitly the case of images that were supported once but are no longer supported (like "openjdk" on s390x and ppc64le).
Ref https://github.com/docker-library/openjdk/issues/364#issuecomment-541193861 (where this idea was proposed :+1:)
---
**WARNING:** THIS IMAGE *IS NOT SUPPORTED* ON THE `s390x` ARCHITECTURE
[![s390x/openjdk build status badge](https://img.shields.io/jenkins/s/https/doi-janky.infosiftr.net/job/multiarch/job/s390x/job/openjdk.svg?label=s390x/openjdk%20%20build%20job)](https://doi-janky.infosiftr.net/job/multiarch/job/s390x/job/openjdk/)
...
=> Add a separate explicit message for architectures which are not supported for an image

postgres/content.md
The current docs link to the _build time_ `/dev/shm` setting ([here](https://docs.docker.com/compose/compose-file/#shm_size)), but should link to the [run time setting](https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir).
=> postgresql: link the correct /dev/shm compose docs

telegraf/content.md
Adds a basic example of how to extend the official image with new packages and use them with Telegraf.
=> Add docs for installing additional commands in telegraf image

oraclelinux/license.md
Our legal team requested the EULA and its URL be version non-specific, so now it is.
=> Updating the EULA URL to point to the new non-versioned location.

sonarqube/content.md
Hello ! We improved the instructions for users using the 7.9.1 version of SonarQube, as the instructions slightly differ from the 8.0 branch.
=> Adding Sonarqube 7.9.1 specific instructions

znc/content.md
https://github.com/znc/znc-docker/issues/19
=> ZNC: IPv6 was enabled a while ago

open-liberty/content.md
* Adding a link to our UBI-based repo on Docker Hub
* Removing the section that explains the specific / older tags, as we're now recommending the `kernel` tag.
=> Update Open Liberty repo description

httpd/content.md
This PR closes docker-library/docs#1615, providing instructions to `cat` the
default upstream configuration from the container and, with redirection, store
a local copy for customization.
The resulting `my-httpd.conf` can then be used in the Dockerfile per the
existing instructions.
=> Provide instructions to obtain the default upstream httpd.conf

elasticsearch/content.md
Links for 6.4 or 6.x should be updated to 7.x or 7.5. And it should be consistent everywhere
=> Link updated on elasticsearch

ubuntu/content.md
Wikipedia changed the links for Ubuntu. It doesn't need to add `(operating system)` anymore. `https://en.wikipedia.org/wiki/Ubuntu` link is good now.
=> Wikipedia link has been updated for Ubuntu.

wordpress/content.md
Link for `Using a Reverse Proxy" in "Administration Over SSL" in upstream's documentation` has been moved to a new URL.
=> Wp links updated

friendica/README-short.txt, friendica/content.md, friendica/github-repo, friendica/license.md, friendica/logo.svg, friendica/maintainer.md, friendica/stack.yml
Part of https://github.com/docker-library/official-images/pull/6446 and https://github.com/friendica/docker/issues/74
=> Add official Friendica docs

debian/content.md
According to https://hub.docker.com/_/debian?tab=description, `debian:latest` is `debian:buster`, but the docs still indicate it's `debian:stretch`.
=> Debian about - Update latest tag to buster

tomcat/content.md
Closes https://github.com/docker-library/tomcat/issues/184
This finally documents https://github.com/docker-library/tomcat/pull/181, officially.
=> Update Tomcat, especially to note the removal of the default webapps

php/content.md
Closes #1639 (carried)
Not sure why I couldn't commit directly to that one (possibly missing "Allow edits from maintainers" checkbox?), but I've preserved the commit authorship here anyhow. :+1:
cc @mlocati
=> Add link to install-php-extensions 3rd party tool

openjdk/content.md
Closes https://github.com/docker-library/openjdk/issues/392
>As of JDK 8 v191 the settings discussed are obsolete, and the container detection is on by default https://www.oracle.com/technetwork/java/javase/8u191-relnotes-5032181.html#JDK-8146115
Also added some `the`'s and other miscellaneous  syntax changes
=> Update for 8u191 changes

postgres/content.md
also add `-e POSTGRES_PASSWORD=mysecretpassword` to most docker run lines
Documentation for https://github.com/docker-library/postgres/pull/658
=> Add section on new POSTGRES_HOST_AUTH_METHOD

golang/content.md
Hi,
I was going through the documentation for Golang lately and I noticed that the version used in examples is not the latest stable.
I thought it would be better to update it.
Please let me know if there are any additional changes needed.
Thanks!
=> Update Golang documentation to use latest stable version (1.13)

sonarqube/content.md
Image update pull request: https://github.com/docker-library/official-images/pull/7528
=> SonarQube 8.2 update docs

postgres/content.md
Current documentations on PostgreSQL image, are a bit unclear about the **required**, **non-empty** `POSTGRES_PASSWORD` environment variable.
Now, more explanations are added and clearer emphasis on important notes are inserted.
=> ✍️ Improve Postgres docs on password/auth environment vars

postgres/content.md
Postgis docker has moved to postgis account.
=> Update links to Postgis repo

wordpress/content.md
The lack of emailing is a good example of an additional extension that is not included in the image. Also referencing [wordpress/issues/30](https://github.com/docker-library/wordpress/issues/30) because it contains good suggestions on the topic.
=> Wordpress: extend doc on PHP extensions

open-liberty/content.md, websphere-liberty/content.md
- Updates the content.md files to more accurately reflect recent changes to the tags provided by `websphere-liberty` and `open-liberty`
@arthurdm I tried to update sections related to specific feature images, like `springBoot2` to use the new tags and best practice approach of building on top of `kernel` and running configure.sh. If you want me to change it to just use `full` instead let me know.
RE: [#149](https://github.com/OpenLiberty/ci.docker/issues/149)
=> Update liberty content to reflect new tags

ghost/content.md
The link to environment variables usage doc on ghost.org is outdated in the Ghost image documentation. This simple pull request updates it with current URL and anchor.
=> Ghost: Update link to environment variables usage doc on ghost.org

nginx/content.md
This PR modifies the description to use environment variables in nginx configuration files.
related to nginxinc/docker-nginx#232
=> Update nginx documentation

thrift/deprecated.md
To be clear, this is not intended to discourage -- the goal of this change is to communicate clearly to users that this image has not seen a substantive update since https://github.com/docker-library/official-images/pull/5411.
Hopefully this will change in the future, especially with the discussions occurring in https://github.com/ahawkins/docker-thrift/issues/12 (ideally directly involved with/approved by upstream :pray::heart:), at which point we'll remove this notice!
=> Add deprecation notice to Thrift image

amazoncorretto/github-repo
We have migrated from separate repositories for Corretto8 docker images and Corretto11 Docker images to a single repository that contains Dockerfiles for both Corretto8 and Corretto11. Updating the Github issue link and Github repository link to reflect the same.
=> Update repositories to point to corretto-docker instead of corretto-8-docker

swarm/deprecated.md
Rendering preview:
---
> Classic Swarm has been archived and is no longer actively developed. You may want to use the Swarm mode built into the Docker Engine instead, or another orchestration system.
(https://github.com/docker/classicswarm#readme)
...
=> Add "Classic Swarm" deprecation notice

swarm/README-short.txt
This is a follow-up to #1738 to make it clear in image listings and `docker search` that this image is deprecated.
I took the deprecation notice and wordsmithed it down to 100 characters so it would fit. :sweat_smile:
(Happy for suggestions if there are better/more preferred ways to adjust the deprecation notice down to 100 characters. :+1: :heart:)
cc @thajeztah @justincormack
=> Update Classic Swarm "short description"

ros/content.md
Since https://github.com/docker-library/official-images/pull/8193 the ros1-bridge images are part of the official library. This updates the references for the README to point to the new image location.
cc @ruffsl 
Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>
=> [ros] update content to reflect new ros1-brige image location

oraclelinux/content.md
Documentation update to address the removal of the `latest` tag for the official Oracle Linux image.
Related: https://github.com/docker-library/official-images/pull/8220
=> Notice of removal of latest tag for Oracle Linux.

websphere-liberty/content.md
Correcting the order where `configure.sh` must be called.  Also, we need a server.xml in the sample.
=> Update WebSphere Liberty documentation

nginx/content.md
The templates script that uses `envsubst` is not available in the current stable version (1.18).
Hope this information saves others some debugging time.
=> Include a "new in" tag to templates section

golang/variant-alpine.md
This adds some Go-specific details, including links to https://github.com/golang/go/issues/19938 and https://github.com/docker-library/golang/issues/250#issuecomment-451201761.
<details>
<summary>Diff:</summary>
```diff
$ git diff --no-index .template-helpers/variant-alpine.md golang/variant-alpine.md
diff --git a/.template-helpers/variant-alpine.md b/golang/variant-alpine.md
index c94e7180f..f14e58f4f 100644
--- a/.template-helpers/variant-alpine.md
+++ b/golang/variant-alpine.md
@@ -2,6 +2,8 @@
This image is based on the popular [Alpine Linux project](https://alpinelinux.org), available in [the `alpine` official image](https://hub.docker.com/_/alpine). Alpine Linux is much smaller than most distribution base images (~5MB), and thus leads to much slimmer images in general.
-This variant …
```
=> Add explicit "golang:alpine" variant description

telegraf/content.md
8083 was the port for the deprecated admin UI which has since then been replaced with Chronograf.
See https://docs.influxdata.com/influxdb/v1.4/tools/web_admin/ and https://docs.influxdata.com/chronograf/v1.4/guides/transition-web-admin-interface/ for more information
=> telegraf: remove deprecated port forwarding

sourcemage/deprecated.md
Refs https://github.com/vaygr/docker-sourcemage/issues/2 (thanks @lag-linaro :heart:)
cc @vaygr -- if the `sourcemage` Docker official image is still something you'd like to continue maintaining, please speak up :wink:
(This also isn't permanent: as the wording implies, we'd be happy to have continued maintenance of this image if it's going to be more active, but even upstream appears to only be slightly more fresh than our image with 0.62-11 in 2017.)
=> Add Source Mage deprecation notice

jetty/README.md, jetty/github-repo, jetty/license.md
Update links to new repository location at https://github.com/eclipse/jetty.docker,
also fix link for the licence information. 
See original PR for this at https://github.com/docker-library/official-images/pull/8241
=> update links in jetty documentation

crux/deprecated.md
This is per the discussion that occurred in https://github.com/docker-library/official-images/pull/5073 and later in https://github.com/docker-library/official-images/pull/7130 -- it sounds like updating the image is going to be a non-trivial endeavor, so this is an attempt to communicate the image status to users.
Hopefully we can revert this soon! :heart:
FYI @ image/repo maintainers: @prologic @lag-linaro @mcharytoniuk @wawrzek
=> Add CRUX deprecation notice

rust/content.md
Following the [best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) we should encourage people to remove the cache after installing dependencies.
=> clean dockerfile layer in example

julia/content.md
This is per https://github.com/docker-library/julia/pull/47#issuecomment-652661869 :heart:
=> Add a dedicated "Julia Support Tiers" callout, explicitly noting Alpine/musl

nginx/content.md
**Related issue**:  nginxinc/docker-nginx#421
**Related pull-request**: nginxinc/docker-nginx#424
=> nginx: add section "Entrypoint quiet logs"

telegraf/content.md
Update the general instructions for monitoring the docker engine host system.
closes #1756
=> Update Telegraf instructions for host monitoring

flink/content.md, flink/get-help.md, flink/github-repo, flink/issues.md, flink/license.md, flink/maintainer.md
Resolves https://issues.apache.org/jira/browse/FLINK-17811
The Hub page of Flink was pretty outdated. This change simplifies the page by mostly linking to the (extensive) documentation on how to use Flink with Docker (which the community is actively maintaining).
=> [flink] update docs to reflect new repository location

bonita/content.md
Documentation for changes of version 7.11.1
This is normal to NOT have any change regarding migration version,
as this is not needed anymore for patch versions.
Related library PR: docker-library/official-images#8525
=> Update Bonita version to 7.11.1

postgres/content.md
Closes https://github.com/docker-library/postgres/issues/327
=> Add note about Alpine locales

php/content.md
Closes https://github.com/docker-library/php/issues/1053
It turns out that these have *never* worked for running as an arbitrary user, and the failure mode is that Apache just happily runs as root instead...  So we should ditch reference to them (instead of noting their caveats) because `--user` is a generally safer and more reliable solution (especially when combined with `--security-opt no-new-privileges`).
=> Remove mention of APACHE_RUN_USER/APACHE_RUN_GROUP which are not a general solution

openjdk/variant-alpine.md
This should help provide clarity for https://github.com/docker-library/openjdk/issues/272 and https://github.com/docker-library/openjdk/issues/211.
=> Improve openjdk-alpine variant information to reflect its early-access nature

redmine/content.md
Closes https://github.com/docker-library/redmine/issues/215
Related to https://github.com/docker-library/redmine/pull/100
=> Add MSSQL variable to Redmine docs

registry/get-help.md
Per conversation with @j0hnst0n :+1:
Example rendering:
-	**Maintained by**:  
[Docker, Inc.](https://github.com/docker/distribution-library-image)
-	**Where to get help**:  
[the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)
-	**Need a free, secure hosted registry?** Try [Docker Hub](https://www.docker.com/pricing).
...
=> Add "Docker Hub" callout to Registry image Quick Reference

ros/content.md
There should be a space between "ROS" and "1" or "2".
=> Fix typos/spelling and uses of 'ROS 1' & 'ROS 2'

caddy/content.md, caddy/get-help.md
Changes relevant to https://github.com/docker-library/official-images/pull/8735
Many thanks to @francislavoie for writing this 😉
Signed-off-by: Dave Henderson <dhenderson@gmail.com>
=> caddy: Updating docs for builder image changes

postgres/content.md
The sentence stated that no environment variables are required to use this image. However, the very first variable - POSTGRES_PASSWORD is stated as required. This is a direct contradiction. This change removes that contradiction and clarifies that the password is required.
=> Remove contradictory sentence in Environment Vars

caddy/content.md
As noted by a user on our community forums, the docker-compose example was missing the volume declarations, leading to errors if copied verbatim. https://caddy.community/t/trouble-running-caddy-in-docker-id-love-some-help/10067/2
=> caddy: Declare volumes in docker-compose example

perl/content.md
A few users of docker-perl have stumbled upon (and getting confused
with) the default /usr/bin/perl shipped by Debian, so put a short note
here explaining why it remains and also better describe how docker-perl
and its tooling is installed/configured.
References:
- https://github.com/Perl/docker-perl/issues/26
- https://github.com/Perl/docker-perl/issues/93
- https://github.com/Perl/docker-perl/issues/94
=> perl: Add note about coexisting with Debian's /usr/bin/perl

rakudo-star/content.md, rakudo-star/github-repo, rakudo-star/maintainer.md
- Fix missing rename to Raku
- Change the scheme of external links to `https`
- Add a link to the [Language Specification](https://github.com/Raku/roast)
- Add a link to a [Wikipedia article](https://en.wikipedia.org/wiki/Rakudo)
- Use [GFM's extended Autolinks](https://github.github.com/gfm/#autolinks-extension-)
=> Update Rakudo Star

kong/content.md
Kong 1.1 added the capability to run Kong without a database, using only in-memory storage for entities: we call this DB-less mode. When running Kong DB-less, the configuration of entities is done in a second configuration file, in YAML or JSON, using declarative configuration.
=> kong: add quick start for db-less

open-liberty/README-short.txt, open-liberty/content.md, websphere-liberty/README-short.txt, websphere-liberty/content.md
Updating documentation for WebSphere Liberty and Open Liberty to cross link the non-official repos.  Addresses https://github.com/OpenLiberty/ci.docker/issues/216
=> Updating Liberty docs

redis/content.md
The provided example may be misleading and will not work in certain
scenarios, where Redis attempts to create additional configuration files
or rewrite existing ones.
See redis/redis#8172.
=> Redis: update configuration bindmount example.

ghost/content.md
And update some outdated bits (like using `volumes-from`).
=> Drop references to ghost 0.x and 1.x

postgres/content.md
Fixes link to avoid extra redirect and additionally link to the documentation for the current version instead of a fixed version (10)
=> Update link to libpq-envvars documentation

.template-helpers/generate-dockerfile-links-partial.tmpl
This was specifically tested against a modified `library/archlinux` file pointing at `GitRepo: https://gitlab.archlinux.org/archlinux/archlinux-docker.git`:
- [`latest`, `base`, `base-20201213.0.11146`](https://gitlab.archlinux.org/archlinux/archlinux-docker/-/blob/f70853f3a094e3c17b37c5d5aabda2ac713deb95/Dockerfile.base)
- [`base-devel`, `base-devel-20201213.0.11146`](https://gitlab.archlinux.org/archlinux/archlinux-docker/-/blob/f70853f3a094e3c17b37c5d5aabda2ac713deb95/Dockerfile.base-devel)
cc @hashworks (this is relevant to your interests :wink:)
=> Add initial support for GitLab-hosted images

postgres/content.md
See https://github.com/docker-library/postgres/pull/713#issuecomment-614854429
=> Add explicit PostgreSQL note about scram-sha-256

haproxy/content.md
This depends on https://github.com/docker-library/haproxy/pull/134 (which adds the `haproxy` user and defaults 2.4+ to `USER haproxy` as documented here).
=> Update haproxy docs to mention USER and bump versions

nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.20.0)
=> [nats-streaming] Release v0.20.0

.template-helpers/template.md
This allows it to show non-PRs too (if they're appropriately labelled).
=> Adjust "label" link/text

perl/content.md
=> perl: Fix typo in Carton example

mediawiki/maintainer.md
https://phabricator.wikimedia.org/T266186 raise some questions on who is
actually maintaining this image. I think it makes more sense to describe this
as something done by MediaWiki community members rather than as by
the Wikimedia Foundation.
cc @davidbarratt and @addshore
=> mediawiki: Update maintainer description

jruby/github-repo
This changed a few months ago.
https://github.com/docker-library/official-images/pull/9319
=> Update JRuby docker repo

influxdb/content.md
docker-library/official-images#9594 has caused a bit of a splash among community members who were using the `latest` tag 😓 mitigate the situation and prevent repeat performances in two ways:
1. Pull the info about upgrading from 1.x to the top of the docs, so anyone who upgrades unintentionally and wants to stick it out can immediately see what they need to do
2. Add version tags to all `%%IMAGE%%` references, so we aren't encouraging anybody to copy-paste a usage of `latest`
=> Rearrange InfluxDB docs so upgrade info is immediately visible.

docker/content.md
More detail is included in the Rootless section so users can see the brief notes on getting it running (without having to peruse the latest discussions)
Closes https://github.com/docker-library/docker/issues/296#issuecomment-790819154
Another issue where instructions weren't clear on what was required for `rootless` https://github.com/docker-library/docker/issues/291
=> Add some notes to the Rootless section

wordpress/content.md
Fixes documentation for changes in https://github.com/docker-library/wordpress/pull/572
Closes https://github.com/docker-library/wordpress/pull/575
=> Adjust wording since Wordpress_db is no longer auto created

mariadb/content.md
The current docs for the MariaDB image incorrectly use the `--port` long form flag which is no longer supported:
=> Update MariaDB docs run command

influxdb/content.md
* Remove use of `:ro`, which doesn't work w/ entrypoint's `chmod`
* Remove reference to "above" from section that was moved to top
Fixes influxdata/influxdata-docker#468
=> Fixup InfluxDB 2.x docs.

hitch/README-short.txt, hitch/content.md, hitch/github-repo, hitch/license.md, hitch/maintainer.md
This is a companion PR to https://github.com/docker-library/official-images/pull/8674
=> Adding Hitch

sonarqube/license.md
The License information for the sonarqube docker image were a little bit misleading as only the community edition is under LGPL.
=> [SonarQube] added licence information

kong/content.md
The existing example code for the postgres container implementation of Kong is broken and it does not work. 
running the following code ( From [here](https://registry.hub.docker.com/_/kong/) ) results in an error.
``` shell 
docker run --rm \
--link kong-database:kong-database \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
-e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
kong kong migrations bootstrap
```
An error stating that 'There is no Postgres Password'  occurs when this command is run. 
Figured out that adding environmental variables POSTGRES_PASSWORD and KONG_PG_PASSWORD to the command arguments fixes the issue.
You can verify whether Kong is working as expected by running `curl http://localhost:8001` after running the 3 commands that were changed in this pull …
=> Added POSTGRES_PASSWORD to fix example code

adminer/content.md
Currently the documentation suggests that for configurable plugins you need to both add the plugin to `ADMINER_PLUGINS` and add config to `/var/www/html/plugins-enabled/`. This is incorrect and causes errors. Instead users should only add config to `/var/www/html/plugins-enabled/`
=> [adminer] Improve docs for ADMINER_PLUGINS interaction with configurable plugins

wordpress/variant-cli.md
Fixes https://github.com/docker-library/wordpress/issues/594
=> Adjust WP-CLI docs for our customized `wp-config.php`

nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.2.2)
=> [nats] Release v2.2.2

percona/content.md
The example commandline was listing a different directory than the rest of the docs.
As someone who copied from the example instead of the text, I can confirm that the directory from the text is the correct one. 😉
=> List correct custom cnf directory in example cmd

couchbase/license.md
Whoops, didn't realise this text was coming from a common template. It's currently [doubled up](https://github.com/docker-library/docs/commit/8677375b458b3c11dc73f995489f4a327b65dbe7#diff-4f6ab524664e06540c0000665ba72488957c67cee2b878f461335ceb59d47d1cR231-R237) as a result.
=> Remove extraneous license-common.md text

mariadb/README-short.txt, mariadb/content.md, mariadb/issues.md
Bulk update largely to cover the new names being available and a few other cleanups.
=> Mariadb update

dart/content.md
Add safeguard for `pub get` when there is no `.dockerignore` and recommend use of a `.dockerignore` file.
=> Update dart content

elixir/github-repo, elixir/maintainer.md
Elixir images had been building from a new Github repo [since October 2020](https://github.com/docker-library/official-images/pull/8979), but URL in the description is still wrong. Let's fix that issue.
=> Fix Elixir image official repo URL

haproxy/content.md
Closes https://github.com/docker-library/haproxy/issues/159
This mirrors php's section for this sysctl https://github.com/docker-library/docs/blob/master/php/content.md#running-as-an-arbitrary-user
=> Add required kernel version for haproxy's sysctl flag 

kong/content.md
rm "First, for fully-compatible with all plugins (e.g. acl, oauth2), Kong requires a running Cassandra cluster (3.x+) or PostgreSQL instance (9.6+) before it starts."
Fixes: https://github.com/Kong/docs.konghq.com/issues/1536
=> [DOCU-1565] rm outdated content on Kong docs

ibmjava/content.md, ibmjava/license.md
Documentation update to include JDK11
=> Enabling IBM JDK11 Docker Images

caddy/README.md, caddy/content.md
This defines the volume as external in order to avoid the problem that `docker-compose down` removes the volume.
This makes sure the volume is not accidentally removed.
This is important, because of the reasons the Readme describes further above. That volume must not be treated as temporary.
See https://docs.docker.com/compose/compose-file/compose-file-v3/#external
Ref https://forums.docker.com/t/why-docker-compose-down-deletes-my-volume-how-to-define-volume-as-external/67433?u=rugk
=> Always persist caddy data directory/volume

sonarqube/content.md
Hello! SonarSourcer here proposing some changes (alongside the Product Team) to the Docs:
* **What is SonarQube?**
* We have Boilerplate guidelines when describing SonarQube we could use, beyond the current 12 word description. It has been added.
* **How to use this image**
* Using “Data Center” Edition rather than DataCenter Edition
* **Docker Host Requirements**
* Due for an update based on [current requirements](https://docs.sonarqube.org/latest/requirements/requirements/#header-5)
* **Get Started in Two Minutes Guide**
* We’ve moved towards wording like **Try Out SonarQube**
* **First Installation**
* The "first" installation is usually when they've tried out SonarQube above? This section is where they get serious about installation (and then configuration), so it's been renamed.
* …
=> Refresh SonarQube Docs

openjdk/content.md, openjdk/variant-oracle.md
OpenJDK images based on OracleLinux 8 instead of OracleLinux 7. This is important because OracleLinux 8 does is using not `yum` package manager but a `microdnf` instead, which could lead to misunderstanding.
=> Fix OpenJDK info about base OracleLinux image version

rabbitmq/content.md
Environment variables are removed with the addition of 3.9: https://github.com/docker-library/rabbitmq/pull/467. Users must provide an ini-style `.conf` file (or an erlang-based `.config`) instead of the environment variables that they were using in `3.8`.  A full `.conf` file is also valid to use with `3.8` and earlier (though old enough versions only support a `.config` file in erlang syntax).
Deprecation notice added to the 3.8 entrypoint script: https://github.com/docker-library/rabbitmq/pull/424 which will also print out the config file it generated. Users can also `docker cp` their current config from their running RabbitMQ container.
Reading https://www.rabbitmq.com/versions.html, I am not certain when the "end of general support" for `3.8.x` will be, so users should likely update …
=> Remove rabbitmq environment variable usage since it is removed in 3.9

mongo/stack.yml
Without `ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"`
<details>
<summary> docker-compose up </summary>
```console
$ docker-compose up -d
Creating network "root_default" with the default driver
Creating root_mongo_1         ... done
Creating root_mongo-express_1 ... done
$ docker logs root_mongo-express_1 2>/dev/null
Welcome to mongo-express
------------------------
Welcome to mongo-express
------------------------
Welcome to mongo-express
------------------------
```
</details>
With `ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"`
<details>
<summary> docker-compose up </summary>
```console
$ docker-compose up -d
Creating network "root_default" with the default driver
Creating root_mongo-express_1 ... done
Creating root_mongo_1         ... done
$ docker logs …
```
=> Include ME_CONFIG_MONGODB_URL

odoo/content.md, odoo/license.md
* Odoo license was updated from AGPL to LGPL a long time ago and never changed here
* Add a section for named volumes
* Adapt docker-compose example to show `secrets` usage
=> Odoo: update documentation to the latest version

eclipse-temurin/content.md
Also add's a statement to clarify the status of JRE images
=> eclipse-temurin: remove duplicate arch description

golang/content.md
Hi,
This is a short PR for bumping the version of Golang to latest stable (1.17).
=> Golang 1.17

nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.5.0)
=> [nats] Release v2.5.0

amazoncorretto/content.md
Add some extra guidance on what to do when a vulnerability is present in an image. We have had frequent contacts regarding this issue.
We added this change to our own corretto-docker repository:
https://github.com/corretto/corretto-docker/pull/69
=> Update amazoncorretto documentation regarding base images

traefik/content.md
=> traefik: minor changes

redis/content.md
The `--appendonly` options has some cons that, IMO, lend the `--save` option to be a more appropriate suggestion in these docs.
I recently found out that in a local `docker-compose`, the `appendonly.aof` file had ballooned to over 1.3GB in my `redis` service, thanks to following the default suggestion here.
I think steering people towards `--save` in this simple example is probably better.
=> redis: prefer "--save" over "--appendonly"

wordpress/content.md
Closes https://github.com/docker-library/wordpress/issues/567
Closes https://github.com/docker-library/wordpress/issues/498
Refs https://github.com/docker-library/wordpress/pull/557, https://github.com/docker-library/wordpress/issues/232#issuecomment-420767663, https://github.com/docker-library/wordpress/pull/628, https://github.com/docker-library/wordpress/issues/473
=> Update WordPress documentation, especially to document read-only deployments

mariadb/content.md
Changed ":tag" to ":latest".
Added user to --env option usage.
Added some notes on cleanup.
=> Minor updates to mariadb/README.md

nats-streaming/README-short.txt, nats-streaming/content.md, nats-streaming/deprecated.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.23.2)
=> [nats-streaming] Release v0.23.2

rabbitmq/content.md
Bringing back a section of the docs detailing the use of some of the more common environment variables: `RABBITMQ_DEFAULT_USER`, `RABBITMQ_DEFAULT_PASS`, and `RABBITMQ_DEFAULT_VHOST`
An addition to https://github.com/docker-library/docs/pull/2012
Closes https://github.com/docker-library/rabbitmq/issues/526
=> Re-add rabbitmq docs section for auth env vars

haskell/content.md
As it does not [currently support ARM64](https://github.com/commercialhaskell/stack/issues/2103).
And clarify old dockerfiles are no longer included in the repo.
Should be merged after https://github.com/docker-library/official-images/pull/11620
=> Note that Haskell ARM64 support does not include the stack tool

mediawiki/README.md, mediawiki/stack.yml
This will make it easier to set up the mediawiki for users not intimately familiar with Docker Stacks conventions for service host naming. I was lucky to find the answer to this problem on https://stackoverflow.com/questions/57312109/mediawiki-docker-official-image-connection-refused-by-mysql, but having it in the docs would make the setup much more smooth.
=> [README] Add comment about database host name

golang/content.md
=> Update Go example to use "go.mod"

push.pl
This has to be slightly more clever than the warning at the beginning to try and avoid weird markdown rendering (so it looks reasonably clean) but it isn't *too* horrible.
Fixes https://github.com/docker/hub-feedback/issues/2220
=> Add "description cut off" warning at end too

nextcloud/content.md
Noticed these while testing #2129 :smile:
(FYI @J0WI @tilosp - I figure you probably don't mind if we just fix these, but if so, we can easily revert :smile:)
=> Fix minor issues in nextcloud code blocks

openjdk/README-short.txt, openjdk/deprecated.md, update.sh
This is an attempt to preemptively/proactively provide a bit more clarity to the OpenJDK image description ahead of https://github.com/docker-library/openjdk/pull/495 and in light of https://github.com/docker-library/openjdk/issues/493 -- this image _really_ is not a good choice for a well-supported Java implementation.
=> Add more description around OpenJDK to make status more clear

varnish/content.md
document the feature introduced in https://github.com/docker-library/official-images/pull/12241
=> [varnish] document install vmods

mono/content.md
The onbuild variant was removed a long time ago, but I wasn't aware of this doc.
=> Remove ONBUILD references from Mono content.md

postgres/content.md
See https://github.com/docker-library/postgres/pull/897
Fixes https://github.com/docker-library/docs/issues/2133
=> Update POSTGRES_HOST_AUTH_METHOD description

mediawiki/stack.yml
Going by example of [Wordpress](https://github.com/docker-library/docs/blob/master/wordpress/stack.yml), I added explicit volume definitions to the example `stack.yml` so it's sufficient to copy and paste the configuration and have persistence.
Fixes #2146.
=> chore(mediawiki): add explicit volume definitions

couchbase/content.md
This change references current version screenshots, and provides a more comprehensive list of client->node ports for examples.
=> Screenshot and port updates

oraclelinux/content.md
I'm trying to make that fact more obvious in the docs that the Docker Hub autogenerated pull command at the top of the page is invalid for this image.
Related: is there any way we can reduce or remove the Quick Start/Tags content at the top of the page? Or move it lower down somewhere? Or fix Docker Hub so it knows not to autogenerate invalid pull commands?
=> [oraclelinux] update docs to improve the first use experience

openjdk/deprecated.md
Closes https://github.com/docker-library/openjdk/issues/505 (see also)
The information in https://snyk.io/jvm-ecosystem-report-2021/ (from that thread) is really interesting/useful IMO.
I think we probably need to try and do _more_ than just this, but maybe this is an OK start?
(I checked some metrics on the five-years-deprecated old `java` image and the amount of _active_ usage still today hurt me :weary::sob:)
=> Adjust OpenJDK image deprecation notice to fully deprecate

caddy/content.md
Allows to caddy to use UDP based HTTP3. See https://github.com/caddyserver/caddy-docker/issues/247
=> Map 443/udp to allow HTTP3

ghost/content.md, ghost/stack.yml
MySQL is the default db for production mode now; to avoid all the envs for connecting to a `mysql` instance on every `docker run`, we'll just use dev mode; stack file still has an example of production mode with a MySQL server.
Related to https://github.com/docker-library/ghost/pull/323
Perhaps we need a specific call out directing to the stack for a production example? Other notes that should be added?
=> Adjust ghost docs to use "development" mode to use sqlite

.template-helpers/variant.sh, debian/content.md
Also make the `content.md` less likely to be out of date.
Related to https://github.com/debuerreotype/docker-debian-artifacts/issues/167
=> Adjust debian doc to not reference `jessie` or `stretch`

mongo/content.md
- `mongo` was removed in 6.0
- `mongosh` is only available in 5+
=> Adjust `mongo` shell command to use `mongosh`

golang/content.md
Update the golang documentation to use the latest version available.
A new major version was released in August: https://go.dev/blog/go1.19
Replaced all the occurrences of `%%IMAGE%%:1.18` by `%%IMAGE%%:1.19`.
=> ⬆ update to golang 1.19

nginx/content.md
The code block contains the paths that should be mapped, `/var/cache/nginx` and `/var/run` for readonly cases. However, the description immediately above the code block also listed two paths. The first, `/var/cache`, would require additional dirs to already exist within the dir. For example, the application will fail to start if the host didn't create an `nginx` dir prior to starting the container.
This change updates the path in the description so it matches the path mapped in the code block and no dirs need to exist before starting the container.
When the path from the description was used instead of the path shown in the code block an error occurred:
```console
$ docker run -d -p 80:80 --read-only -v $(pwd)/nginx-cache:/var/cache -v $(pwd)/nginx-pid:/var/run nginx
```
Results in the …
=> nginx - Fix container path for cache dir to prevent error mkdir() "/var/cache/nginx/client_temp" failed (2: No such file or directory)

openjdk/README-short.txt
This is a successor/companion to https://github.com/docker-library/docs/pull/2162 to make the pre-release-only status of the `openjdk` image hopefully more clear.
=> Update OpenJDK short description to be more precise

mariadb/content.md
This is due to the idea in https://github.com/MariaDB/mariadb-docker/issues/458 and the merge of https://github.com/docker-library/official-images/pull/13184.
=> added MariaDB _HASH environment variables

mariadb/content.md
Order the manditory MARIADB_ROOT_PASSWORD* by decreasing strength.
Add ref MARIADB_PASSWORD_HASH to MARIADB_ROOT_PASSWORD_HASH for setting password.
=> mariadb: MARIADB_ROOT_PASSWORD_HASH to set of manditory vars

centos/README-short.txt, centos/deprecated.md
Closes https://github.com/docker-library/official-images/issues/11679
=> Add deprecation notice for CentOS

nextcloud/README.md, nextcloud/content.md
[README] In `docker-compose exec db sh -c "mysql -u USER -p PASSWORD nextcloud < /dmp"`:
Replaced `-p` with `--password` because of: _'If you use the short option form (-p), you cannot have a space between the option and the password.'_ - mysql man page.
Also replaced `-u` with `--user` for consistency.
This fix is necessary since the command otherwise failes because of a wrong password.
=> Fix mysql import in nextcloud readme

.template-helpers/get-help.md
Also, link directly to their "What topics can I ask about here?" pages instead of to a search.
=> Link to more Stack Exchange sites

mariadb/README.md, mariadb/content.md
In the current version, reading this may cause confusion.
=> Readme Typo when referring to pre-existing db folder

nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.25.2)
=> [nats-streaming] Release v0.25.2

postgres/content.md
Postgres 15 has support for ICU locales which Alpine uses as noted by @lukaromih https://github.com/docker-library/postgres/issues/1004#issuecomment-1280559846
>The key is in version 15 of Postgres. And the timing couldn't be better, because it's only like 3-4 days old.
>As mentioned in [PostgreSQL 15.0 release docs](https://www.postgresql.org/docs/release/15.0/):
>> Allow [ICU](https://www.postgresql.org/docs/15/locale.html) collations to be set as the default for clusters and databases (Peter Eisentraut)
>> 
>> Previously, only libc-based collations could be selected at the cluster and database levels. ICU collations could only be used via explicit COLLATE clauses.
Testing the example Dockerfile
```console
$ docker build -t postgres:test - << EOF
FROM postgres:15-alpine
ENV …
```
=> Add Alpine locale information for Postgres 15

jetty/README.md, jetty/content.md
I have removed this part of the docs, and I don't think we want to add HTTP/2 module by default. They will need other configuration for this like setting up a keystore.
=> remove line in jetty docs about JDK9 and HTTP2

ubuntu/content.md, ubuntu/github-repo
Ubuntu base images rootfs tarballs are now fetched from Launchpad Git
repository. The location https://partner-images.canonical.com/oci/ is no
longer used. Update links in the documentation to refer to the
https://git.launchpad.net/cloud-images/+oci/ubuntu-base Git repository
URL instead.
The Launchpad Git repository URL is also set in github-repo file. This
shouldn't matter because the fact that an URL is a GitHub URL is used
only to fetch badges from open-source CI/CD services, and in case the
URL is not a GitHub URL, the HTTP request will just fail, and no badge
will be included.
closes #2227
=> ubuntu: Update Git references to Launchpad

nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.9.8)
Signed-off-by: Waldemar Quevedo <wally@synadia.com>
=> [nats] Release v2.9.8

push.pl
> Now that we're only supporting 3 images, would it be possible to get the supported tags listed on https://hub.docker.com/_/neo4j?tab=description again?
- @jennyowen, https://github.com/docker-library/official-images/pull/13593#issue-1464644606
=> Remove "neo4j" short tags special case

vault/content.md
… to actually be directly usable and fix backend to current wording of storage.
Current version leaves new user of HashiCorp image questioning on how to progress. Vault starts without any listener, doesn't open any port and is hence not usable for any quickstart or test. With this change, a user can directly call localhost:8200 in his browser and initialize and navigate in Vault UI. 
Further, its important to change wording from `backend` to `storage` as there aren't many examples of Vault JSON config out there and with the example naming the storage  `backend` it might be misleading for new users that HCL configs can't be translated easily to JSON configs.
=> Improve Hashicorp Vault docker run example for server mode

postgres/content.md
This change is related to and to be merged together with https://github.com/docker-library/postgres/pull/1018.
=> Update "arbitrary --user" notes for postgres

README.md, generate-repo-stub-readme.sh
Apply changes for https://github.com/badges/shields/issues/8671. This will need to also be used to generate all of our repo readme files to fix https://github.com/docker-library/python/issues/779.
Also drop unused travis and appveyor urls.
=> Fix badges urls

ghost/content.md
This fixes the database file path so that it will be in the volume when using development mode.
https://github.com/docker-library/ghost/discussions/365#discussioncomment-4596332
=> Adjust ghost persistent storage examples

rust/content.md
I originally opened this here: https://github.com/rust-lang/docker-rust/issues/129
Old Rust versions are referenced, when you just update them without touching anything else, there's a good chance your resulting image will not work as later builders are using bullseye but the examples still use buster which results in a mismatch in Glibc version.
=> Update Rust versions in examples

convertigo/README-short.txt, convertigo/content.md
=> Convertigo doc minor changes

golang/content.md
Update the golang documentation to use the latest version available.
A new major version was released on the 1st of February: https://go.dev/blog/go1.20
Replaced all the occurrences of `%%IMAGE%%:1.19` by `%%IMAGE%%:1.20`.
=> ⬆ update to golang 1.20

kong/content.md
Add documentation for using `read-only` mode with Kong.
=> docs(kong): add read-only mode reference

vault/content.md, vault/deprecated.md
I'd like to update our docker image docs to warn about an impending switch to publishing only the Verified Publisher images per a deprecation notice here: https://developer.hashicorp.com/vault/docs/deprecation.
I've also gotten the Verified Publisher documentation (https://hub.docker.com/r/hashicorp/vault) updated though it doesn't have all the fancy updates from the update script.
=> Add deprecation notice to Vault

telegraf/content.md
Replace Telegraf Official Docs link with https://docs.influxdata.com/telegraf/latest/get_started/
Reported in https://github.com/influxdata/docs-v2/issues/4715
=> Fix incorrect link for Telegraf Official Docs

ghost/content.md
Fix typo, updating _X-Forwared-Host_ to _X-Forwarded-Host_.
=> Fix typo in "Production mode" docs

ubuntu/maintainer.md
Given the new OCI-based image submission workflow, the Maintainance of the Ubuntu container image can solely be assigned to Canonical.
=> Update Ubuntu's maintainer.md

ubuntu/content.md
feat: Bionic going into ESM
Bionic is going into ESM on the 31st of May 2023, so this pull request must be merged after this date.
Signed_Off_By: samir.akarioh@canonical.com
=> Bionic ESM

php/content.md
Also update any mentioned module versions so that they build with the latest PHP.
=> Update mentioned php versions that are EOL

postgres/content.md
The content of this PR should be self-explaining.
Signed-off-by: Matthias Riegler <matthias.riegler@ankorstore.com>
=> fix: rephrase the Postgres PGDATA documentation and add a warning

ubuntu/content.md
Ubuntu 22.10 (Kinetic Kudu) reaches End of Life on July 20 2023. Remove
it from the README.
=> Ubuntu 22.10 (Kinetic Kudu) EOL

perl/content.md
- https://github.com/Perl/docker-perl/issues/140
=> perl/content.md: Note about WORKDIR issue with Debian 12 based image

eclipse-temurin/content.md
Will be available after https://github.com/adoptium/containers/pull/392 is merged.
=> Add documentation for custom CA certificates for Temurin

almalinux/content.md
We've [updated our goals](https://almalinux.org/blog/future-of-almalinux/) and are no longer 1:1 with RHEL. The foundation also owns everything related to the OS, so I wanted to clarify that in the description. Thanks!
=> Updating the information around AlmaLinux OS

golang/content.md
Update the golang documentation to use the latest version available.
A new major version was released on the 8th of August: https://go.dev/blog/go1.21
Replaced all the occurrences of `%%IMAGE%%:1.20` by `%%IMAGE%%:1.21`.
=> chore: ⬆ update to Go 1.21

push.pl
Logos upload is not currently available on our arch-specifc namespaces. Follow up to https://github.com/docker-library/docs/pull/2373. This restores the condition that stops us from attempting to upload logos to the arch specific namespaces.
```console
converting adminer/logo.png to adminer/logo-120.png
POST to https://hub.docker.com/api/media/repos_logo/v1/amd64%2Fadminer/upload failed: {"message":"not enough permissions"}
```
=> Only upload logos to `library/`

caddy/content.md
=> Add NET_ADMIN documentation

nginx/content.md
First of all, thank you for the great effort to maintain this marvelous project. 
When I first saw this document, I didn't understand the meaning of `This can also be accomplished`.
I actually misinterpreted it as "Copying the default nginx configuration file from a running container to the host system can also be accomplished" , but the docker file looked doing the opposite.
So I tried to improve some points:
* "copying the default conf" relates to both mounting and building , so I moved it to the head
* It is not  necessarily "complex", so I omitted it.
=> Improve explanation about how to customize Nginx configuration

ghost/stack.yml
This is adding named volumes to the example docker-compose file, since otherwise the uploaded data is easily lost, same for the DB.
=> Update Ghost stack.yml to have persistent data

convertigo/content.md
=> Convertigo: add the ENABLE_JDWP_DEBUG environment variable

golang/content.md
The Go toolchain uses the local git installation to fetch archives of modules from Git servers directly. My company commits large files using Git LFS which happen to be part of our Go module source tree. Without _git-lfs_ installed, the local git installation does not automatically resolve those files which causes "_checksum mismatch_" against the committed `go.sum`.
This pull-request aims to ease the strain on developers that encounter that unfortunately under-documented scenario, and lower the barrier of entry for companies to the Golang world.
=> Update golang/content.md to explain when and how to install git-lfs

mongo/content.md
Closes docker-library/mongo#656.
=> mongo: add security section

amazonlinux/content.md, caddy/content.md, cassandra/content.md, drupal/stack.yml, ghost/stack.yml, joomla/stack.yml, lightstreamer/content.md, nextcloud/content.md, postfixadmin/stack.yml, redmine/stack.yml, satosa/content.md, wordpress/stack.yml
And some `stack.yml` version updates.
Carry/fix all these PRs that changed `README` instead of `content`:
- fixes https://github.com/docker-library/docs/pull/2357
- fixes https://github.com/docker-library/docs/pull/2381
- fixes https://github.com/docker-library/docs/pull/2382
- fixes https://github.com/docker-library/docs/pull/2336
=> Typo fixes

registry/content.md
Replace references to Docker HTTP API V2 with OCI distribution spec links.
CC: @thaJeztah
=> update: registry readme

mysql/content.md, percona/content.md
The link http://dev.mysql.com/doc/en/adding-users.html appears to be broken.
I think the correct link should be https://dev.mysql.com/doc/refman/en/creating-accounts.html
=> Fix broken links for mysql

nextcloud/content.md
Looking at https://github.com/nextcloud/docker/blob/d1dbc77e0b5e851105cf8606942e74b7d21fe682/.config/smtp.config.php it is clear that `SMTP_HOST`, `MAIL_FROM_ADDRESS` and `MAIL_DOMAIN` must be set.
=> NextCloud: Mention minimal SMTP configuration in README.md

nginx/content.md
Currently, instructions to copy the default configuration from the nginx container to the host uses three commands. This can be done more efficiently with one command (assuming the presence of "cat" in the container which should be a safe).
Update the instructions to use the single command.
=> nginx: Update command to generate host config file

wordpress/content.md
The previous wording is incorrect. The value is not embedded verbatim, but is evaluated by php's eval() function:
```if ($configExtra = getenv_docker('WORDPRESS_CONFIG_EXTRA', '')) {
eval($configExtra);
}```
=> Corrected info how WORDPRESS_CONFIG_EXTRA is put into effect

golang/content.md
A new version of Go was released on the 6th of February:  
https://tip.golang.org/doc/go1.22
=> Update to Go 1.22

python/variant-slim.md
Add an image-specific slim variant section for Python. This overrides the default description of a slim variant.
The image-specific description clarifies when `pip install` might fail in slim variants of the Python image.
=> python: Add note on `pip install` in slim variants

influxdb/README-short.txt, influxdb/content.md, influxdb/variant-data.md, influxdb/variant-meta.md
This PR revises the image description, product names, and procedures and code samples for using the InfluxDB Docker Hub image for InfluxDB v2.
- Updates description to be consistent with marketing and documentation
- Add specificity for product/version naming ("InfluxDB v2")
- Promote automated setup and other Docker-specific aspects
- Replace deprecated `influxd print-config` with `influx server-config` and note the Operator token requirement
- Use the version `2` tag in code samples
- Use canonical `/influxdb/v2` in Docs links
- Rely on `docs.influxdata.com` for Quick Start guide and InfluxDB features not specific to Docker
- Add a section to define ports and file system
=> fix(influxdb-v2): Revise and update image description and v2 instructions

mysql/stack.yml
The mysql_native_password plugin is now disabled-by-default (and adminer is in a sad state).
=> Update MySQL example stack

chronograf/content.md, kapacitor/content.md
In a recent release we stopped running as the root user, but provided users a way to change this if they wanted to via an env variable. This adds this variable to the docs.
=> Update chronograf and kapacitor: Specify how to run as root

open-liberty/README-short.txt, websphere-liberty/README-short.txt
The reference to Ubuntu 18.04 in the short description of websphere-liberty and open-liberty is outdated, hence remove it.
=> Update short description of websphere-liberty and open-liberty

joomla/content.md, joomla/github-repo, joomla/stack.yml
Update Joomla Docker documentation to improve clarity and enhance configuration options
- Changed container network configuration to use Docker networks instead of linking containers.
- Introduced new environment variables for database configuration:
- `JOOMLA_DB_PASSWORD_FILE`: Path to a file containing the database password.
- `JOOMLA_DB_TYPE`: Database type with options for "mysqli" and "pgsql".
- Added environment variables for auto-deployment configuration:
- `JOOMLA_SITE_NAME`, `JOOMLA_ADMIN_USER`, `JOOMLA_ADMIN_USERNAME`, `JOOMLA_ADMIN_PASSWORD`, `JOOMLA_ADMIN_EMAIL`
- `JOOMLA_EXTENSIONS_URLS`, `JOOMLA_EXTENSIONS_PATHS`
- `JOOMLA_SMTP_HOST`, `JOOMLA_SMTP_HOST_PORT`
- Updated port mapping instructions to reflect the new network setup.
- Corrected the Dockerfile reference link for …
=> Joomla Update

Dockerfile
(verified successful/working while testing https://github.com/docker-library/docs/pull/2465)
=> Update `push.pl` runtime to Perl 5.39 and Debian Bookworm

ruby/content.md
Previous: https://github.com/docker-library/docs/pull/2051
3.0 images are not build/updated anymore
-------
In a separate commit, I've dropped mentions of evn variables that were once set but aren't anymore. See https://github.com/docker-library/ruby/pull/209 and https://github.com/docker-library/ruby/pull/306
=> Update examples from "ruby:3.0" to "ruby:3.3"

.template-helpers/generate-dockerfile-links-partial.sh, .template-helpers/generate-dockerfile-links-partial.tmpl
Especially with Docker Hub's new stylesheets, the tag listing is *really* compressed and hard to scan/read, especially on the really extreme examples like `tomcat`.
This adjusts the line-spacing such that they should have a little more breathing room overall.
=> Add newlines between tag groups so they get better line-spacing

ubuntu/content.md
Update the docs to remove releases that have reached EOL, and to add Noble and Oracular
=> docs(ubuntu): close Mantic and backfill Noble and Oracular

sapmachine/content.md
Architectures are now part of the "Quick reference (cont.)" section. Update the "Overview" section.
=> SapMachine: minor content update on architectures and "Overview" section.

adminer/README-short.txt, adminer/deprecated.md
See https://www.youtube.com/watch?v=OrOtiu_nfHE&lc=Ugy8pAL8wgAL3_iKkzZ4AaABAg.9pj_kQ2rkuw9pp813OyHha (youtube comment), https://github.com/TimWolla/docker-adminer/issues/147, and https://github.com/vrana/adminer -- upstream is not actively maintained (and has not been for years now).  We should reflect/document that status accurately on Docker Hub.
=> Add `adminer` deprecation notice

php-zendserver/README-short.txt, php-zendserver/deprecated.md
Quoting https://github.com/docker-library/official-images/pull/16941#issuecomment-2195225594:
> it's been three years since this image has had any meaningful updates (https://github.com/docker-library/official-images/pull/10276)
Closes https://github.com/docker-library/official-images/pull/16941
Closes https://github.com/docker-library/official-images/pull/17016
=> Officially deprecate `php-zendserver` image

clefos/README-short.txt, clefos/deprecated.md
cc @nealef for a vibe and wording check :heart:
(I'm honestly kind of sad to see it go, because it was fun and even sometimes helpful for catching bugs/assumptions to have a DOI that _didn't_ support `amd64`, but alas - end of an era :smile:)
Refs https://github.com/docker-library/official-images/pull/7964#issuecomment-2253636315
=> Officially deprecate ClefOS

mono/README-short.txt, mono/deprecated.md
- https://github.com/docker-library/official-images/pull/12682#issuecomment-1875991681
- https://github.com/docker-library/official-images/pull/17091#issuecomment-2201099734
:disappointed:
(This is easy to revert if y'all want to revive the image! :heart:)
=> Deprecate `mono` image (due to maintainer inactivity)

sonarqube/README.md, sonarqube/content.md
In order to make it easier for developers who want to run SonarQube in a container, I think it is worth indicating the port binding when running the docker run command.
Our exemple are using the tag 10.6.0-community
=> docs: update readme to indicate the port binding

solr/README-short.txt, solr/content.md
Keeps these descriptions up to date with changes the Apache Solr project made recently in their README, documentation, website, etc.
Additional context at:
- https://solr.apache.org/
- https://issues.apache.org/jira/browse/SOLR-16295
- https://github.com/apache/solr/pull/2692
=> Update README description for Apache Solr

redis/github-repo
This PR updates the `git-repo` URL to the updated location of the Redis URL.
=> Update Redis repository URL to the Correct URL

redis/content.md, redis/maintainer.md
- Remove the 32 bit variant section which is no longer relevant.
- Remove the section on Redis-Stack which is no longer relevant.
- Update the maintainer information to [Redis LTD](https://redis.io/).
Relates to https://github.com/docker-library/docs/pull/2488
=> Revisit Redis's Content

caddy/content.md
Last August unexpected behaviour of the graceful reload feature was discussed in this [upstream issue](https://github.com/caddyserver/caddy/issues/5735) and a fix proposed alongside the suggestion to add that fix to the docs. This has not yet happened but should be solved by this PR.
This is my first contribution here, so if there is anything I should address to finalize this PR, I ask you kindly to let me know.
This one resolves #1858 as well.
=> Update docs for Caddy image with a fix to its reload feature

nginx/content.md
I used this in class. My students were missing the build command, because it is a bit hidden in the text. I suggest making it more obvious that the image needs to be built before running it.
=> Clarify how to build and run

ibm-semeru-runtimes/content.md
The example in https://hub.docker.com/_/ibm-semeru-runtimes has incorrect tag, which is corrected as part of this update.
=> Correct IBM Semeru Tag info in Example 

sonarqube/content.md
Just fixing some typos in the README.
=> Fixes some typos on SonarQube's README

backdrop/content.md, bonita/content.md, cassandra/content.md, convertigo/content.md, drupal/content.md, eggdrop/content.md, emqx/content.md, friendica/content.md, geonetwork/content.md, ghost/content.md, joomla/content.md, matomo/content.md, mediawiki/content.md, monica/content.md, mysql/content.md, nextcloud/content.md, percona/content.md, phpmyadmin/content.md, storm/content.md
Not an exhaustive update (didn't want to touch the `stack.yml` stuff yet, could do in a follow-up) but updated references to old `docker-compose` binary and changed the filename from `docker-compose.yml` to `compose.yaml`, where it made sense to do so.
=> docs: update deprecated/outdated compose syntax and filenames

wordpress/stack.yml
Based on [this reference](https://docs.docker.com/reference/compose-file/version-and-name/), there is no need to compose file version.
=> fix: remove obsolete docker compose file version

nats/content.md
This PR adds examples for enabling NATS [JetStream](https://docs.nats.io/nats-concepts/jetstream) and optionally persisting data to a volume.
=> nats: Add JetStream usage examples

traefik/content.md
This PR updates the Traefik readme
=> Update traefik readme

redmine/content.md
See https://github.com/docker-library/redmine/pull/339#issuecomment-2581009265
=> Remove more Redmine passenger variant leftovers

redmine/content.md
Update description relative to https://github.com/docker-library/redmine/pull/365
=> Update `REDMINE_SECRET_KEY_BASE` usage/description

ros/content.md
Replaces: https://github.com/docker-library/docs/pull/2522
Fixes: https://github.com/ros-infrastructure/rosindex/issues/456
=> Update index.ros.org links

eclipse-temurin/content.md
The examples are showing JDK version 21 but the description text above states JDK version 11
=> fix: typo on version name

docker/content.md, docker/variant-rootless.md
Also, add an explicit note about how to switch the UID/GID and drop the note about 19.03 (long since EOL).
Closes https://github.com/docker-library/docker/issues/528
=> Move rootless notes to a variant stub

yourls/content.md
=> Fix YOURLS documentation link in README content

docker/variant-rootless.md
Verified properly this time:
```console
$ cat Dockerfile
FROM docker:dind-rootless
USER root
RUN set -eux; \
sed -i -e 's/^rootless:x:1000:1000:/rootless:x:1234:5678:/' /etc/passwd; \
sed -i -e 's/^rootless:x:1000:/rootless:x:5678:/' /etc/group; \
chown -R rootless ~rootless
USER rootless
$ docker buildx build --pull --tag tianon/dind1234 .
...
#6 exporting to image
#6 exporting layers done
#6 writing image sha256:114395aef97f155e9d229b3b2328e2149ae689b18f115cb6e3900ed469c7fdad done
#6 naming to docker.io/tianon/dind1234 done
#6 DONE 0.0s
$ docker run -dit --rm --name dind --privileged tianon/dind1234
508c64a236d9ef97f6e533128ab1ea16928f79f354286d45483b96039094cc41
$ docker logs --tail=2 dind
INFO[2025-03-03T20:55:39.874459873Z] API listen on /run/user/1234/docker.sock …
```
=> Fix typos in dind-rootless sed expressions

golang/variant-tip.md
This describes [the "tip" variant](https://github.com/docker-library/golang/pull/531), but most notably provides a rough estimate for how often it's updated.
(https://github.com/docker-library/golang/issues/464#issuecomment-2730113332)
=> Add a `golang:tip` variant section

odoo/content.md
As I use docker-compose.yml example, I saw an indentation problem.
Is that OK?
=> fix(README): Fix indent problem for environments keyword

rabbitmq/README.md, rabbitmq/content.md
The link was probably outdated and didn't redirect to the right section in the documentation.
=> Update link to --secret option in README.md

mediawiki/stack.yml
This PR follows from discussion on https://phabricator.wikimedia.org/T393171 and makes slight formatting improvement following https://phabricator.wikimedia.org/T254405
=> MediaWiki example `docker-compose.yml`: remove obsolete "version" attribute

postgres/content.md
The `/bin/bash` shebang points does not point to the correct path for bash in the container. Because of this, the initialization scripts will not run. Changing to `/usr/bin/env bash` fixes this problem.
Alternatively `/usr/bin/bash` would also work.
=> postgres: Fix incorrect shebang in example initialization script

ubuntu/content.md
Update the docs to remove releases that have reached EOSS, and to add Plucky and Questing
=> docs(ubuntu): close Focal and add Plucky and Questing

eclipse-temurin/content.md
Closes: https://github.com/adoptium/containers/issues/556
=> Update `eclipse-temurin` docs about CA certs on non-root images

redis/content.md
Update documentation to reflect changes in the upcoming Redis image version (8.0.2)
=> Update documentation for Redis

update.sh
Unfortunately we don't have a good replacement for these, but they're very, very outdated, so this removes them.
=> Remove outdated per-arch Jenkins badges

sonarqube/content.md
Hello team.
We updated some links in our README.
=> DOC-2073 update URLs to the Sonar docs

ros/content.md, ros/metadata.json
Refreshes the ROS documentation using updated links, cleans out old content, and improves the demo examples.
Related:
- https://github.com/docker-library/docs/pull/1381
=> [ROS] Update Official Docker image docs

ubuntu/content.md
Oracular has reached EOL on July 10: https://fridge.ubuntu.com/2025/07/10/ubuntu-24-10-oracular-oriole-reached-end-of-life-on-10th-july-2025/
=> docs: close Oracular

yourls/compose.yaml, yourls/content.md, yourls/github-repo
* Reflect port change in compose file and readme
* Tweak command-line examples to make them clearer and more explicit
* Add a section about the volumes
* Typos and small improvements
=> Reflect latest changes in YOURLS docs

mongo/compose.yaml
Just one more place where Mongo documentation was outdated.
=> Remove not used mongo-express env. variables
