docker-library/docs

- rails/README.md
- rails/content.md
Add example for creating a new Rails project.
> Rails bootstrap example

- thrift/README-short.txt
- thrift/README.md
- thrift/content.md
- thrift/license.md
- thrift/user-feedback.md
- update.sh
I'm not sure if I'm following the correct format. It seems there  is a `content.md` and `README.md` in the folder. They seem to share similar content. `README.md` usually contained the most information so I created
one for Thrift.
> Add thrift

- httpd/content.md
docs for https://github.com/docker-library/httpd/pull/2
ping @tianon
> Add https info to httpd

- websphere-liberty/content.md
Correct identation that was messing up the paragraph numbering.
> Correct indentation

- php/content.md
Silly mistake made by me.. :scream:
> fix a typo (to enable jpeg support)

- .template-helpers/compose.md
- update.sh
- wordpress/README.md
- wordpress/content.md
- wordpress/docker-compose.yml
This includes an example `docker-compose.yml` for WordPress.
> Add some official docker-compose.yml scaffolding

- Dockerfile
> Remove --verify to combat more BackPAN irritation

- README.md
For people contributing to docker-library/docs the first time, it is quite difficult to understand the complete process of changing the documentation. With this small improvement I hope it is easier to use the markdownfmt.sh script. It took me some time to figure out how to properly contribute to the docs and thus I hope it is easier for the next one.
> Add description how to use markdownfmt.sh

- docker-dev/README.md
- docker-dev/content.md
> Point users from docker-dev to dockercore/docker for an up-to-date development environment

- glassfish/README.md
- update.sh
```java
/** no comment **/
```
> Add glassfish url

- postgres/content.md
No update.sh to expedite review.  Made for https://github.com/docker-library/postgres/issues/20#issuecomment-89798157.
@geraldodev Does this help? Do you have other suggestions?  Feel free to make PRs to this repo if you would like to improve the documentation on any of the Official Images.
> Add info to postgres for locale setup

- jetty/README.md
- jetty/content.md
cf. appropriate/docker-jetty#9
> Update Jetty docs to clarify webapp deployment

- hello-world/README.md
- hello-world/content.md
- hello-world/update.sh
- scratch/README.md
This also explains what goes into the sausage a little bit. :horse: :pig2: :dog2:
> Update "scratch" and "hello-world" to be more complimentary

- fedora/content.md
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
> update fedora/content.md about f20 going EOL

- rabbitmq/content.md
Fixes https://github.com/docker-library/rabbitmq/issues/6 (see https://github.com/docker-library/rabbitmq/issues/6#issuecomment-97721548; thanks @dumbbell! :heart:)
This also documents the change in https://github.com/docker-library/rabbitmq/pull/30 which makes cookies much easier to use.
> Update rabbitmq image documentation

- mysql/content.md
Double tab indentation required to add code in a list
> Add code highlighting to volume mount example

- celery/content.md
See https://github.com/docker-library/official-images/pull/907.
> Add documentation for how to use Celery and Redis together

- sentry/content.md
Docs for https://github.com/docker-library/sentry/pull/15
> Add new sentry setup

- push.pl
> Fix for deprecated mojo function

- push.pl
> Update push.pl for the new v2 hub!

- push.pl
See https://hub.docker.com/_/redmine/ for an example.
> Add some temporary description trimming

- ros/content.md
Adding deployment example as well as use cases and suggestions.
Also adding dockerfile syntax highlighting.
> Adding Deployment example to ROS docs

- update.sh
> Support svg logos too

- websphere-liberty/content.md
Corresponds to https://github.com/docker-library/official-images/pull/958
> Document new websphere-liberty images

- docker/content.md
cc @jpetazzo :heart: :heart_eyes:
> Add a link to Jérôme's dind blog post to our "docker" image description

- update.sh
> sentry: update README to point to new repo

- registry/content.md
> Add note about DTR to registry description

- websphere-liberty/content.md
- websphere-liberty/license.md
Docs updates for https://github.com/docker-library/official-images/pull/1117
> Revert websphere-liberty docs for IBM JRE

- bonita/content.md
- update.sh
fix Bonita BPM logo link and add bonita in otherRepos into update.sh
> update Bonita doc

- mysql/content.md
refers to https://github.com/docker-library/mysql/commit/14f165596ea8808dfeb2131f092aabe61c967225#diff-17ed820d5141a5e8565a0431e5385dae
Signed-off-by: Frank Sachsenheim <funkyfuture@riseup.net>
> mysql: Adds a note about docker-entrypoint-initdb.d

- .template-helpers/variant-alpine.md
https://github.com/docker-library/golang/pull/68
> Add text to explain "alpine" variants!

- neo4j/README-short.txt
- neo4j/content.md
These are some docs improvements based on user feedback after our initial official release.
> Updates to Neo4j documentation

- clojure/content.md
> Fix a typo in clojure README

- jenkins/content.md
Get the docker hub readme aligned with the image one
> [jenkins] Align with image readme

- golang/content.md
Closes #400
Thanks @Starefossen :heart:
> Fix golang:onbuild "COPY" path

- cassandra/content.md
Fixes docker-library/cassandra#42
Thanks @hotstepper13!
> Fix cassandra volume path

- ros/content.md
Also adding an equivalent docker-compose example.
> [ROS] Update for new Network functions in Docker v1.9

- postgres/content.md
Fixes docker-library/postgres#90.
> Mention POSTGRES_DB in postgres/content.md

- mageia/content.md
@juanluisbaptiste for sanity check
> Updated docs for Mageia 5

- owncloud/content.md
Fixes docker-library/owncloud#22
> owncloud: Update docs for volume persistence

- sentry/content.md
- sentry/variant-onbuild.md
See also https://github.com/docker-library/official-images/pull/1338
/cc @tianon @yosifkit I assume the README.md file is autogenerated from these components? plz correct me if I'm wrong. :)
> Update docs for sentry 8

- php/content.md
Closes #418
Closes docker-library/php#170
Fixes #323
> Add docs for PECL and "other" extensions installation in PHP

- busybox/content.md
See also https://github.com/docker-library/official-images/pull/1347 and https://github.com/docker-library/busybox/pull/7.
cc @jpetazzo
> Describe the updated Busybox variants in a little more detail

- nginx/content.md
This PR is in response to https://github.com/nginxinc/docker-nginx/pull/59 where I was asked to document this feature.
> Added documentation on how to use envsubst to generate nginx config

- odoo/content.md
Hello,
This PR is related to #430
Regards
> Odoo: clarification of upgrading process

- haskell/content.md
To go with https://github.com/docker-library/official-images/pull/1392
> Mention Stack and fix inline Dockerfile.

- debian/content.md
> Add more/better content to the Debian description

- sentry/content.md
Fixes getsentry/docker-sentry#42
> Update sentry docs

- mongo/content.md
Closes https://github.com/docker-library/mongo/pull/48
> Add a section about "--auth" to the mongo documentation

- odoo/content.md
Closes https://github.com/docker-library/docs/pull/338
> Avoid hard-coded IP specification in odoo

- README.md
RE https://github.com/docker-library/official-images/pull/1342#issuecomment-189841143
> clarify logo.png

- sentry/content.md
> sentry: fix env variables docs

- oraclelinux/README.md
- oraclelinux/content.md
Also switch to HTTPS for the main Oracle Linux home page.
> Updated Oracle Linux docs with Yum Server name change

- sentry/README.md
- sentry/content.md
Fixed formatting for code blocks so they can be properly rendered by github
> Update README.md for Sentry block

- postgres/content.md
This documents the POSTGRES_INITDB_ARGS environment variable added in #132.
> Document POSTGRES_INITDB_ARGS env var

- .template-helpers/template.md
- .template-helpers/user-feedback.md
As discussed in https://github.com/tianon/docker-brew-ubuntu-core/issues/41#issuecomment-184967383
> Adjust a couple URLs to clarify the process slightly more

- golang/content.md
Thanks for pointing this out, @fboyer! :heart:
> Update/remove golang:cross references

- websphere-liberty/content.md
Updated sample to use Java EE7
> Updated sample to use Java EE7

- haproxy/content.md
`docker kill` things. :smiling_imp:
> Document haproxy SIGHUP reloading

- debian/content.md
> Add a note about the new debian/eol image

- redis/content.md
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>
> modify redis docs to use modern linking with dns/hostname

- php-zendserver/content.md
Update Zend Server documentation to state licensing details.
> Update Zend Server documentation

- neo4j/content.md
We have moved the docs to the Neo4j website.
> Release Neo4j 3.0.0

- couchdb/content.md
corresponding to https://github.com/docker-library/official-images/pull/1711
Thank you :)
> update couchdb docs

- crate/content.md
- crate/user-feedback.md
Hi - we have completely changed our Docker overview page in order to reflect the switch to Alpine Linux and make it easy for people to get into Crate.
Cheers, Claus
> Overhaul of Crate.IO's overview page

- arangodb/content.md
> Add some note when creating a base image

- .template-helpers/generate-tag-details.pl
See https://github.com/docker/docker/issues/22436 for more details.
I did my testing with `tianon/build-args:1.10.3`:
```console
$ docker pull tianon/build-args@sha256:71cbced1991f9cde80dd208420cd74edab57044ad4f3f6a71f75742b9141815d
```
-	Total Virtual Size: 0.0 B
-	Total v2 Content-Length: 2.3 MB (2320908 bytes)
```dockerfile
ADD file:614a9122187935fccfa72039b9efa3ddbf371f6b029bb01e2073325f00c80b9f in /
```
-	Created: Fri, 06 May 2016 14:56:49 GMT
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:d0ca440e86378344053c79282fe959c9f288ef2ab031411295d87ef1250cfec3`
-	v2 Content-Length: 2.3 MB (2320212 bytes)
-	v2 Last-Modified: Fri, 06 May 2016 14:57:17 GMT
```dockerfile
ARG test=test
```
-	Created: Wed, 18 May 2016 22:31:35 GMT
-	Parent Layer: …
> Handle the fallout of flattened strings from Docker 1.10+ (as best we can currently)

- .template-helpers/generate-tag-details.pl
> Add proper support for schemaVersion 2 (including manifest lists) in generate-tag-details.pl

- .template-helpers/generate-tag-details.pl
- hello-world/tag-details.md
Whoops :innocent:
```console
$ ./markdownfmt.sh -d hello-world/tag-details.md
$ 
```
> Appease markdownfmt

- owncloud/content.md
- owncloud/docker-compose.yml
Closes https://github.com/docker-library/owncloud/issues/73
> Clarify owncloud data storage and add simple example docker-compose.yml

- memcached/content.md
> Update memcached wiki link to new location

- .template-helpers/variant.sh
> Fix "variant" parsing for 2822-based manifests

- hello-seattle/README-short.txt
- hello-seattle/content.md
- hello-seattle/github-repo
- hola-mundo/README-short.txt
- hola-mundo/content.md
- hola-mundo/github-repo
See also https://github.com/docker-library/official-images/pull/1899 and https://github.com/docker-library/hello-world/pull/16.
> Add vanity DockerCon variations of hello-world

- arangodb/content.md
Paths have changed with the new version..
see https://github.com/docker-library/official-images/pull/1893
> Adjust persistent volume path

- mariadb/content.md
- mysql/content.md
- percona/content.md
> Add some basic documentation for MYSQL_RANDOM_ROOT_PASSWORD and MYSQL_ONETIME_PASSWORD

- owncloud/docker-compose.yml
> Upgrade owncloud's docker-compose.yml to version 2

- docker/content.md
> Change Docker-in-Docker README perspective

- rabbitmq/content.md
Related to https://github.com/docker-library/rabbitmq/pull/65
> Added support for HiPE in RabbitMQ docker

- php/content.md
Depends on https://github.com/docker-library/official-images/pull/1942
> Add explanation to php for `docker-php-source`

- registry/README.md
- registry/content.md
Signed-off-by: Richard Scothern <richard.scothern@gmail.com>
> Update tag documentation

- nats/content.md
to reflect the current v0.9.2 release
> [NATS] Update outputs and command line options

- nuxeo/content.md
Documentation introduced by https://github.com/docker-library/official-images/pull/2040 (waiting for merge)
> Add documentation on new parameters

- websphere-liberty/content.md
Doc update to go with https://github.com/docker-library/official-images/pull/2043
> Remove mention of websphere-liberty:common image

- nats/content.md
Official image PR: https://github.com/docker-library/official-images/pull/2069
> [NATS] Update output and command lines for new release v0.9.4

- .template-helpers/variant-windowsservercore.md
> Add "variant-windowsservercore" for discussing our new "windowsservercore" variants and how to use them

- httpd/content.md
See https://github.com/docker-library/httpd/issues/9.
> Adjust "httpd" examples to use "-d" ("caught SIGWINCH, shutting down gracefully" on terminal resize)

- ubuntu/content.md
> Note where the Ubuntu tarballs come from and what "latest" points to

- logstash/content.md
Closes https://github.com/docker-library/logstash/issues/34
> Add an example Dockerfile to logstash

- mysql/content.md
Closes https://github.com/docker-library/mysql/issues/137
cc @ltangvald
> Add a blurb about using "mysql" to connect to non-Docker or remote instances

- bonita/content.md
https://github.com/docker-library/official-images/pull/2085
> Add explanation to migrate Bonita BPM in 7.3.x

- hello-world/content.md
according to the new structure of repo - new filename is hello.c
> hello.asm->hello.c rename

- docker/content.md
> Add a bit of color about Storage Drivers to the DinD docs

- ruby/content.md
Closes https://github.com/docker-library/ruby/issues/45
> Add a note about Encoding in Ruby

- kong/README.md
- kong/content.md
> Update Kong documentation

- solr/content.md
Update the Solr README content with content from https://github.com/docker-solr/docker-solr/blob/master/README.md
> update solr content

- README.md
> Add README link/badge for our Jenkins "update.sh and push.sh" job

- debian/content.md
See also https://github.com/tianon/docker-brew-debian/issues/45.
> Add a note to Debian regarding locales included by default and especially how to make others available

- irssi/github-repo
See https://github.com/jessfraz/irssi/pull/10
> Update "irssi" repo

- redmine/content.md
- redmine/docker-compose.yml
```
$ docker-compose up
..... [much truncate]
redmine_1  | [2016-09-30 23:28:56] INFO  WEBrick 1.3.1
redmine_1  | [2016-09-30 23:28:56] INFO  ruby 2.2.5 (2016-04-26) [x86_64-linux]
redmine_1  | [2016-09-30 23:28:56] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
```
> Add docker-compose file for redmine

- crux/deprecated.md
cc @prologic -- if we don't hear from you shortly, we'll be merging this :pray:
> Deprecate "crux" due to maintainer inactivity

- README.md
> Add note that "bashbrew" is required for running "update.sh"

- tomee/content.md
Hi all
As indicate in here http://tomee.apache.org/commercial-support.html , ManageCat is another commerical support company behind the Apache TomEE project. We would also like to include ManageCat to this README file in addition to the another commercial company Tomitribe for supporting the project.
Thanks 
Gurkan
> Update the TomEE content.md File

- ubuntu/content.md
See also https://github.com/tianon/docker-brew-ubuntu-core/issues/67#issuecomment-253570049 (and the following discussion).
> Add a small note about what "ubuntu:devel" is an alias for

- elasticsearch/content.md
Closes https://github.com/docker-library/elasticsearch/issues/98
See also https://github.com/docker-library/elasticsearch/pull/127
> Add a section to Elasticsearch about host setup (especially the necessary sysctl)

- haproxy/README.md
- haproxy/content.md
This has been mentioned in the comments twice, so I thought I'll add it for people to save them time wondering why their port configuration doesn't seem to be working :)
> Add a note about publishing haproxy's input port to the host

- php/content.md
> Update PHP memcached example to properly compile again

- logstash/content.md
> Add logstash plugin install example

- nats/content.md
Details can be found [here](https://github.com/nats-io/gnatsd/releases/tag/v0.9.6)
> [nats] Release v0.9.6

- websphere-liberty/content.md
Sorry - this is going to annoy me otherwise!
> Outdent header

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.3.6)
> [nats-streaming] Release v0.3.6

- drupal/content.md
- drupal/docker-compose.yml
Closes https://github.com/docker-library/drupal/issues/56
> Add an initial docker-compose.yml for drupal

- nats-streaming/content.md
Essentially a bug fix release.
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.3.8)
> [nats-streaming] Release v0.3.8

- bonita/content.md
updates links and migration part
related to https://github.com/docker-library/official-images/pull/2598
> Updates Bonita BPM doc

- silverpeas/mailing-list.md
- silverpeas/user-feedback.md
- update.sh
Also, move `silverpeas/mailing-list.md` to use `silverpeas/user-feedback.md` instead.
> Finish mailing-list removal from #572

- redis/content.md
Fixes https://github.com/docker-library/redis/issues/88
Thanks @cihanb!
> Adjust redis wording to properly attribute sponsors

- bonita/content.md
related to https://github.com/docker-library/official-images/pull/2648
> update Bonita BPM and migration tool versions

- hello-world/content.md
> issue-836 wrong path in hello world docs

- docker/content.md
Pushing pull request as per [issue](https://github.com/docker-library/docker/issues/45)
fixes https://github.com/docker-library/docker/issues/45
> Updated docker content.md to reflect updated docker privilege URL

- nginx/content.md
The first commit is a suggestion for improvement. I came across this as I wanted to fix https://github.com/nginxinc/docker-nginx/issues/126.
> Nginx: preciser "daemon off" & improvement

- ubuntu/content.md
Closes https://github.com/tianon/docker-brew-ubuntu-core/issues/78
> Copy Debian's "Locales" section for Ubuntu (with very minor changes)

- storm/content.md
- storm/docker-compose.yml
> Apache Storm 1.1.0

- owncloud/content.md
Closes https://github.com/docker-library/owncloud/pull/68
> Add a short blurb about using "occ"

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.4.0)
> [nats-streaming] Release v0.4.0

- mysql/content.md
> Updated MySQL docs re: _FILE env vars

- rabbitmq/content.md
Closes docker-library/rabbitmq#151
> Add a note/warning about RabbitMQ+HiPE+Alpine

- gradle/content.md
> comment out note about reusing cache for now

- generate-repo-stub-readme.sh
> Update "generate-repo-stub-readme.sh" to skip "unknown" Travis badges and to include AppVeyor badges where applicable!

- ubuntu/content.md
See also https://github.com/docker-library/official-images/pull/2720 and https://github.com/docker-library/official-images/issues/2323.
FYI @OddBloke
> Add a short blurb to explain what "ubuntu:rolling" is

- adminer/maintainer.md
- spiped/maintainer.md
Sorry again, @TimWolla :disappointed:
I've updated both `adminer` and `spiped` -- wanna take a look and make sure I got it right this time? :pray:
> Fix TimWolla's last name

- chronograf/content.md
I updated the description and changed the link at the bottom. Otherwise looks good!
> Make small wording changes for chronograf 1.3

- rabbitmq/README-short.txt
Team RabbitMQ feels this description is more to the point
(and does not use blanket marketing statements).
> Alter RabbitMQ image description

- nginx/content.md
I did some minor editing around the headers, and across the text as well. Mostly for clarity and consistency.
> Some essential grammar fixes.

- rapidoid/content.md
Related to PR: docker-library/official-images#3034
> Updated Rapidoid examples for v5.3.5

- debian/content.md
- debian/github-repo
> Update Debian github-repo and talk about debuerreotype!

- nginx/content.md
Hey, we've had this free service for quite some time already - it's called NGINX Amplify. It's a free tool that can be used to visualize nginx performance metrics, analyze nginx config, see what recommendations and security advisories are available, and such. I'm hoping this is ok by you guys. /Cc @thresheek
> Added a section on monitoring nginx containers with Amplify.

- nextcloud/content.md
> Nextcloud: Improve README with the default host port

- redmine/content.md
- redmine/stack.yml
- wordpress/content.md
See also https://github.com/docker-library/docs/pull/913.
> Convert "redmine" to use "docker stack deploy"

- nextcloud/content.md
https://github.com/nextcloud/docker/pull/101
> Nextcloud: Fix README.md typo

- convertigo/content.md
> Add the missing "m" for the "-Xmx4096m".

- nextcloud/content.md
https://github.com/nextcloud/docker/pull/106
> Nextcloud: Fix Typos

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.5.0)
> [nats-streaming] Release v0.5.0

- nextcloud/content.md
https://github.com/nextcloud/docker/pull/112
> Nextcloud: Update README.md to use nextcloud:fpm image in FPM example

- nextcloud/content.md
https://github.com/nextcloud/docker/pull/120
> Nextcloud: Add hint for using the nextcloud Console

- debian/content.md
"the time of this writing" is always now
> Update latest to strech in prose

- nats/content.md
Details can be found [here](https://github.com/nats-io/gnatsd/releases/tag/v1.0.0)
> [nats] Release v1.0.0

- nextcloud/content.md
https://github.com/nextcloud/docker/pull/132
> Nextcloud: Fix path to themes folder in the README

- jenkins/deprecated.md
see https://github.com/jenkinsci/docker/issues/515
> deprecate official docker image

- bonita/content.md
related to https://github.com/docker-library/official-images/pull/3417
> update Bonita BPM version and describe DB_DROP_EXISTING and BIZ_DB_DROP_EXISTING

- php/content.md
Addresses comments made here: https://github.com/docker-library/php/issues/246
> Adds example on setting a docroot with Apache

- .template-helpers/variant.sh
This also changes the `buildpack-deps` detection so that it only triggers the "this image is large with lots of packages" description if some tag of the image being described is `FROM buildpack-deps` (and _not_ simply `-curl` or `-scm` variants), which adjusts `golang`, `haxe`, `influxdb`, `kapacitor`, `openjdk`, and `telegraf` to correctly have the shorter non-`buildpack-deps`-referencing description.
> Fix an assumption of repos having a "latest" tag

- nextcloud/content.md
> [Nextcloud] Added readme entry for auto config

- influxdb/content.md
> Update influxdb documentation with database initialization

- ghost/content.md
- ghost/stack.yml
Closes https://github.com/docker-library/ghost/issues/93
Closes https://github.com/docker-library/ghost/issues/36
> Add initial ghost/stack.yml which demonstrates environment-variable-based configuration

- composer/content.md
> amend Composer documentation

- nats/content.md
Details can be found [here](https://github.com/nats-io/gnatsd/releases/tag/v1.0.4)
> [nats] Release v1.0.4

- postgres/content.md
Closes https://github.com/docker-library/postgres/issues/349
> Add a "Docker Secrets" section to PostgreSQL too

- geonetwork/stack.yml
- mariadb/content.md
- mariadb/stack.yml
- mysql/stack.yml
- percona/content.md
- percona/stack.yml
This includes both `stack.yml` and the "Secrets" usage description.
Closes https://github.com/docker-library/mariadb/issues/131
> Resync mariadb and percona docs with mysql

- adminer/content.md
see TimWolla/docker-adminer#15
see TimWolla/docker-adminer#16
> Update list of supported Adminer drivers

- buildpack-deps/license.md
- cassandra/license.md
- crux/license.md
- debian/license.md
- ghost/license.md
- hello-seattle/license.md
- hello-world/license.md
- hola-mundo/license.md
- jenkins/license.md
- mariadb/license.md
- mongo-express/license.md
- mysql/license.md
- neurodebian/license.md
- percona/license.md
- postgres/license.md
- ubuntu/license.md
- wordpress/license.md
> Add several missing "license.md" files (especially for docker-library images)

- opensuse/license.md
Ref: #1046
Signed-off-by: Aleksa Sarai <asarai@suse.de>
/cc @flavio -- Can you double-check that this is correct?
> opensuse: add license information

- mageia/license.md
https://github.com/docker-library/docs/issues/1046#issuecomment-339526046 :+1:
(thanks @juanluisbaptiste :heart:)
> Add mageia/license.md

- nats-streaming/content.md
Adding multi-arch support.
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.6.0)
> [nats-streaming] Release v0.6.0

- nginx/license.md
Refs https://github.com/docker-library/docs/issues/1046
> Add NGINX license.md

- bonita/content.md
- bonita/stack.yml
to finish answering to https://github.com/Bonitasoft-Community/docker_bonita/issues/5
> add docker-compose example for bonita

- amazonlinux/license.md
> Add license.md for amazonlinux

- php/content.md
> Clarify that all variants include the PHP cli

- .travis.yml
- .travis/check-markdownfmt.sh
- .travis/check-ymlfmt.sh
- adminer/stack.yml
- bonita/stack.yml
- elasticsearch/stack.yml
- geonetwork/stack.yml
- joomla/stack.yml
- kibana/stack.yml
- mariadb/stack.yml
- markdownfmt.sh
- mediawiki/stack.yml
- mysql/stack.yml
- percona/stack.yml
- postgres/stack.yml
- storm/stack.yml
- ymlfmt.sh
- zookeeper/stack.yml
This is still a WIP -- trying to get Travis to a state where it's verifying this properly. :+1:
> Add "ymlfmt" for enforcing consistent YAML whitespace

- redis/content.md
added module repos for simplified use of open source repos for the modules that have docker images now. will add more as new modules repos arrive.
> updated modules information for simpler getting started

- zookeeper/stack.yml
More details in https://github.com/31z4/zookeeper-docker/pull/27
> Correct Zookeeper stack example to work with a user-defined network

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.7.0)
> [nats-streaming] Release v0.7.0

- mysql/content.md
See https://github.com/docker-library/mysql/issues/81 for more discussion around this topic.
> Point to a couple Official Images "wait-for-db" examples

- convertigo/content.md
Simple update of definitions of our software.
> Update description of MBaaS.

- bonita/content.md
related to https://github.com/docker-library/official-images/pull/3868
> update Bonita and migration tool versions

- rabbitmq/content.md
I'm not sure if this is the best place to add this, but it wasn't explicitly listed anywhere and would be helpful to newcomers unfamiliar with RabbitMQ.
> Adding note about default rabbitmq port

- wordpress/content.md
Fixes https://github.com/docker-library/wordpress/issues/225
> Added WORDPRESS_DB_PASSWORD_FILE to readme

- influxdb/content.md
Fixes influxdata/influxdata-docker#180.
> Fix a typo in the influxdb documentation

- open-liberty/content.md
Image PR: https://github.com/docker-library/official-images/pull/3909
> Add docs for new tags for open-liberty image

- kong/content.md
* PostgreSQL version
* Fix markdown syntax issue
> chore(*) update left overs

- nextcloud/content.md
https://github.com/nextcloud/docker/pull/192
> [Nextcloud] Fixed typos

- nextcloud/content.md
https://github.com/nextcloud/docker/pull/199
> [Nextcloud] Added recursive flag to chown command

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.7.2)
> [nats-streaming] Release v0.7.2

- nats-streaming/content.md
This release introduces clustering feature as a beta.
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.8.0-beta)
> [nats-streaming] Release v0.8.0-beta

- nextcloud/content.md
https://github.com/nextcloud/docker/pull/262
> [Nextcloud] Grammar fix in README.md

- nats/content.md
Details can be found [here](https://github.com/nats-io/gnatsd/releases/tag/v1.0.6)
> [nats] Release v1.0.6

- maven/content.md
Remove onbuild references
Fix https://github.com/carlossg/docker-maven/issues/68
> Update maven docs

- jruby/content.md
- pypy/content.md
- ruby/content.md
> Remove a few more onbuild references

- mediawiki/issues.md
Requested by community [here](https://phabricator.wikimedia.org/T179660).
> Make issues file per request

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.9.0)
> [nats-streaming] Release v0.9.0

- oraclelinux/README-short.txt
- oraclelinux/content.md
- oraclelinux/github-repo
* update pointer to new container-images build repo
* update examples to use 7
Signed-off-by: Jesse Butler <jesse.butler@oracle.com>
> Update oraclelinux docs

- nats/content.md
Details can be found [here](https://github.com/nats-io/gnatsd/releases/tag/v1.1.0)
> [nats] Release v1.1.0

- traefik/content.md
Hello,
This PR updates Traefik documentation
Related to https://github.com/docker-library/official-images/pull/4257
/cc @vdemeester @emilevauge @ldez
Cheers
> Update Træfik documentation

- postgres/content.md
See https://github.com/docker-library/postgres/issues/340.
> Add a blurb about installing PostgreSQL extensions

- ubuntu/content.md
Include the contents of the `sources.list` for the latest LTS release.
> Update docs for Ubuntu 18.04

- nats-streaming/content.md
- nats/content.md
Be explicit about "docker run -p" and NATS servers -p parameter.
> [nats][nats-streaming] Clarify use of -p

- mysql/content.md
Closes https://github.com/docker-library/mysql/issues/273
> Update MySQL configuration docs to be more accurate

- openjdk/content.md
Closes https://github.com/docker-library/openjdk/issues/135
> Add note about OpenJDK, shells, and bad environment variables

- wordpress/content.md
> Add WORDPRESS_DEBUG note

- httpd/content.md
Making it more newbie friendly
By adding a port map
So feedback could be seen
on localhost:8080
> Updated httpd/content.md

- alpine/content.md
Closes https://github.com/gliderlabs/docker-alpine/issues/409
> Update Alpine docs (links, sizes, versions, etc)

- ibmjava/content.md
Bump IBM Java version to 1.8.0_sr5fp16 (8.0.5.16).
> Turn on container support by default

- postgres/content.md
Docs for https://github.com/docker-library/postgres/pull/452
> Update postgres initdb information about sourcing scripts vs executing then

- websphere-liberty/license.md
Updating license to version 18.0.0.1
> Updating license to latest version

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.10.0)
> [nats-streaming] Release v0.10.0

- amazonlinux/content.md
ref https://github.com/docker-library/official-images/pull/4502
> Update Amazon Linux docs for AL2 release

- nats/content.md
Details can be found [here](https://github.com/nats-io/gnatsd/releases/tag/v1.2.0)
> [nats] Release v1.2.0

- swipl/github-repo
> Point SWI-Prolog to docker repo

- mysql/stack.yml
adminer has connectivity issues with mysql versions from 8.0.
> Update stack.yml to fix adminer connection

- httpd/content.md
Closes https://github.com/docker-library/httpd/issues/108
> Update httpd SSL documentation

- zookeeper/content.md
Please merge https://github.com/docker-library/official-images/pull/4716 first.
> Document `autopurge` Zookeeper configuration

- wordpress/content.md
Pointing to https://github.com/docker-library/wordpress/issues/256, inspired by https://github.com/docker-library/wordpress/issues/322. :+1:
> Add a note about WP-CLI's "USER"

- wordpress/content.md
See https://github.com/docker-library/wordpress/pull/142.
> Add documentation for WORDPRESS_CONFIG_EXTRA

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.11.0)
> [nats-streaming] Release v0.11.0

- wordpress/content.md
Closes docker-library/wordpress#299
> Add MySQL SSL note to WordPress description

- zookeeper/content.md
Please merge https://github.com/docker-library/official-images/pull/4828 first.
> Document logging dir config in Zookeeper

- rabbitmq/content.md
> Remove HiPE warning for Alpine

- convertigo/content.md
> Use CouchDB 1.7.1 instead of 1.6.1

- websphere-liberty/license.md
Updating licenses for Liberty 18.0.0.3
> Updating Liberty's licenses

- cassandra/content.md
This also attempts to de-emphasize the use of our fiddly environment variables.
> Adjust Cassandra configuration section to emphasize using a custom configuration file

- odoo/content.md
- odoo/license.md
Hello,
Here is an update of the Odoo docker image documentation.
Thanks
> Odoo: update documentation to latest version

- flink/content.md
See https://github.com/docker-flink/docker-flink/commit/e347e0c0e933f753b9a30c630a1e1e06d36c47db
> Remove flink local mode

- ghost/content.md
Mention ghost-cli is not working out of the box, refer to @acburdine comment explaining why on https://github.com/docker-library/ghost/issues/156
> Add note about ghost-cli not intended to work

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.11.2)
> [nats-streaming-server] Release v0.11.2

- ghost/content.md
Resolves https://github.com/docker-library/ghost/issues/158
> Add section about upgrading Ghost

- websphere-liberty/content.md
Once the [non-root PR](https://github.com/docker-library/official-images/pull/4959) goes through, we can merge this one for the related documentation.
> Updating documentation

- .template-helpers/generate-dockerfile-links-partial.tmpl
Needs https://github.com/docker-library/official-images/pull/4980 (which is now merged, built, and updated on all our servers).
This implements what's described in https://github.com/docker-library/go-dockerlibrary/pull/16#issuecomment-407905834.
> Add "ArchFile" for differing "File:" values

- clojure/content.md
Addresses https://github.com/Quantisan/docker-clojure/issues/48
> Add info about boot and tools-deps variants of clojure image

- crux/deprecated.md
- crux/maintainer.md
- More versions coming very shortly
- Support for more architectures coming shortly
> Un-deprecate Crux

- convertigo/content.md
> Use Couchdb 2.3.0 instead of 1.7.1

- couchdb/content.md
Improved documentation, based on examples from others in this repo.
> Updates for CouchDB 2.3.0

- websphere-liberty/license.md
Updating license to point to `18.0.0.4`
> Updating license

- solr/content.md
Fixes https://github.com/docker-library/docs/issues/1396
> Update Solr doc to match the README.md

- odoo/content.md
To fix https://github.com/odoo/odoo/issues/27447. Sort the environtment variables as well.
> Add 'POSTGRES_DB=postgres' to the custom example

- docker/content.md
- postgres/content.md
- redis/content.md
Closes https://github.com/docker-library/memcached/issues/44
> Drop/adjust a few explicit EXPOSE references (mostly implied, not really adding value)

- nats/content.md
Details can be found [here](https://github.com/nats-io/gnatsd/releases/tag/v1.4.1)
> [nats] Release v1.4.1

- opensuse/README-short.txt
- opensuse/deprecated.md
https://github.com/docker-library/official-images/issues/5371
> Also mention deprecation in opensuse/README-short.txt

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.12.0)
> [nats-streaming-server] Release v0.12.0

- fedora/content.md
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
> Update link to Fedora kickstart

- elasticsearch/github-repo
Apologies, the last PR only included updates for the issue text and not the repo ref itself.
> Corrected repo reference

- backdrop/content.md
- drupal/content.md
- joomla/content.md
- mediawiki/content.md
- wordpress/content.md
- yourls/content.md
> Remove "Repository Links" links 😞

- postgres/content.md
And adjust section ordering
RE: https://github.com/docker-library/postgres/issues/193
> Add warnings to postgres about an already initialized data directory

- yourls/content.md
- yourls/stack.yml
> Document YOURLS_USER and YOURLS_PASS for YOURLS image

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.12.2)
> [nats-streaming] Release v0.12.2

- express-gateway/content.md
> Fix command name for Express Gateway plugins

- kong/content.md
to resolve https://github.com/Kong/docker-kong/issues/76
> kong: specify the KONG_PG_HOST environment variable

- open-liberty/content.md
Updating docs to help users after PR https://github.com/docker-library/official-images/pull/5587 goes through.
> Update Open Liberty docs

- alpine/content.md
- alpine/github-repo
- alpine/maintainer.md
cc @ncopa
These docs could really use a lot more care and attention, but this at least brings them in line with the move to https://github.com/alpinelinux/docker-alpine and your official maintenance.  Does this look OK?  Anything you'd like me to change while I'm in here?  (I don't mind making more changes if you want, or if you'd rather take over and make these changes yourself -- happy to help!)
> Update a few minor Alpine bits to reflect the new reality

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.14.0)
> [nats-streaming] Release v0.14.0

- oraclelinux/content.md
With thanks to @tianon for teaching me how to ~fish~ check my Markdown format before submitting a pull request.
> Updating Oracle Linux documentation with the correct URLs.

- golang/content.md
Cross-compile your app inside the Docker container
I have tried to run this code， but it did not work. 
So I changed in my way.
> FIX: Cross-compile

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.14.1)
> [nats-streaming] Release v0.14.1

- open-liberty/content.md
Synchronizing with changes that went into WebSphere Liberty via PR #1474
> Updating Open Liberty docs

- zookeeper/content.md
Depends on https://github.com/docker-library/official-images/pull/5903.
> Update Zookeeper documentation

- websphere-liberty/content.md
Adding a link to our Enterprise Capabilities section.
> Updating WebSphere Liberty docs

- nextcloud/content.md
Merging recent changes from https://github.com/nextcloud/docker/commits/master/README.md
Should be merged with https://github.com/docker-library/official-images/pull/5824
cc @tilosp
> Update NextCloud docs

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.14.2)
> [nats-streaming] Release v0.14.2

- mariadb/content.md
- mysql/content.md
- percona/content.md
The command is originally from a popular gist: https://gist.github.com/spalladino/6d981f7b33f6e0afe6bb
> mysql/mariadb/percona: note a way to restore data from dump file.

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.14.3)
> [nats-streaming] Release v0.14.3

- zookeeper/stack.yml
Addresses https://github.com/31z4/zookeeper-docker/issues/65.
> Add missing client port to Zookeeper stack.yml

- nginx/content.md
This depends on https://github.com/docker-library/official-images/pull/6020 to be merged first.
> nginx: Documented UID changes and how to run as an arbitrary user

- nats/content.md
This is a major new release. Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.0.0)
> [nats] Release v2.0.0

- neo4j/content.md
We changed our base image, so would like to update our readme to help our users deal with the changes.
> Change Neo4j read me

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.15.1)
> [nats-streaming] Release v0.15.1

- bonita/content.md
related to https://github.com/docker-library/official-images/pull/6097
> Update Bonita doc for 7.9

- convertigo/content.md
> Removes 32 bit for now and adds `COOKIE_PATH` documentation.

- adoptopenjdk/content.md
> adoptopenjdk: add windows-amd64 to arch list

- matomo/content.md
Just a small update to address the feedback in https://github.com/matomo-org/docker/issues/69
> Update bits of matomo docs

- yourls/content.md
Includes the link to official documentation for variable descriptions.
Closes #1520
> Improve YOURLS documentation about env variables

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.0.2)
> [nats] Release 2.0.2

- matomo/content.md
https://github.com/matomo-org/matomo/pull/13676
https://github.com/matomo-org/docker/commit/13a4200cd68099e050dd4022edc876f2f96d4959
> Add Matomo database envs to docs

- jobber/README-short.txt
- jobber/content.md
- jobber/github-repo
- jobber/license.md
- jobber/maintainer.md
Official Images PR: https://github.com/docker-library/official-images/pull/3972
> Add documentation for Jobber

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.0.4)
> [nats] Release 2.0.4

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.16.0)
> [nats-streaming] Release v0.16.0

- traefik/content.md
Update documentation for Traefik v2.
Closes #1468
> Update Traefik documentation.

- sonarqube/content.md
Hello guys, 
Edit : this is now ready for review and merge :)
We opened a [PR on the library side](https://github.com/docker-library/official-images/pull/6778), please accept both PR in a close timebox :)
> SONAR-12445 improve doc for folders binding, first install, upgrade

- geonetwork/variant-postgres.md
Document a new environment variable available to configure the database name. Available once 3.8.2 release PR https://github.com/docker-library/official-images/pull/6916 is merged.
> Add POSTGRES_DB_NAME documentation

- crate/content.md
- crate/license.md
does what it says on the tin :)
> Copyedits and link fixes

- websphere-liberty/content.md
Updating UBI link and removing outdated tags description.
> Update WebSphere Liberty content

- kong/content.md
Created new PR to get rid of reverting or CI/CD errors
> Unify Shell-Syntax

- php/content.md
https://github.com/friendica/docker/pull/78#issuecomment-529210776
> [PHP] Document default extensions

- .template-helpers/get-help.md
> Slack URL updated

- drupal/content.md
Fixes https://github.com/docker-library/drupal/issues/162
Used `postgres:11` due to https://www.drupal.org/project/drupal/issues/3094738
> Update Drupal docs

- rapidoid/deprecated.md
Per discussion in https://github.com/docker-library/official-images/pull/4667#issuecomment-565212257.
cc @nmihajlovski
> Add rapidoid deprecation notice

- tomee/content.md
> Links fixed for Apache TomEE

- convertigo/README-short.txt
- convertigo/content.md
Following the convertigo-7.6.6 release. Thx !
> Convertigo: Update product description. Add the COOKIE_SECURE environment variable.

- sonarqube/content.md
> Sonarqube linkfix

- sonarqube/content.md
Hello, a small fix of the instructions for the 8.1 version.
> Fix SonarQube 8.1 instructions with tag

- rust/content.md
> update doc to show working example

- arangodb/content.md
- Better explain passing of command line arguments
- Update documentation links
- Minor formatting/punctuation improvements
> [ArangoDB] Update arangodb/content.md

- yourls/content.md
Change the starting link to access the admin interface
ref: https://github.com/YOURLS/docker-yourls/issues/35
> Improve YOURLS documentation

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.1.4)
> [nats] Release v2.1.4

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.17.0)
> [nats-streaming] Release v0.17.0

- websphere-liberty/license.md
> Update WebSphere Liberty license file

- redmine/content.md
- redmine/stack.yml
Closes https://github.com/docker-library/redmine/issues/192
> REDMINE_SECRET_KEY_BASE is required for Docker Swarm

- yourls/content.md
Fix YOURLS_DB_PREFIX variable documentation
Ref https://github.com/YOURLS/docker-yourls/issues/45
> Update YOURLS content

- friendica/content.md
- Replace "SITENAME" with "SMTP_DOMAIN" config
Based on https://github.com/docker-library/official-images/pull/7550
> Friendica doc improvement

- composer/content.md
OSX issue has been fixed for later versions
> Update composer docs

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.1.6)
> [nats] Release v2.1.6

- nextcloud/content.md
Successor of #1394.
See nextcloud/docker#560.
> nextcloud: Add Secrets Section, markdownfmt

- ghost/content.md
Closes https://github.com/docker-library/ghost/issues/217
> Specify Ghost admin url

- rakudo-star/content.md
track language rename and refresh some links
> Update rakudo-star content

- logstash/github-repo
- logstash/issues.md
Similar to https://github.com/docker-library/docs/pull/1429 + https://github.com/docker-library/docs/pull/1431
> Update logstash github-repo and issues to be similar to elasticsearch + kibana

- .template-helpers/template.md
-	**Maintained by**:  
[Jessie and Tianon (of the Docker Community)](https://github.com/jessfraz/irssi), [with the appreciation of the Irssi Project](https://twitter.com/GeertHauwaerts/status/559131523145035776)
-	**Where to get help**:  
[the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](http://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)
-	[`1.2.2`, `1.2`, `1`, `latest`](https://github.com/jessfraz/irssi/blob/773216139cd3685fd710b77dc7d4ee26ec9fb187/debian/Dockerfile)
-	[`1.2.2-alpine`, `1.2-alpine`, `1-alpine`, `alpine`](https://github.com/jessfraz/irssi/blob/4eb15e5f0583e58b326282ce0b1454aa5df1cf31/alpine/Dockerfile)
-	**Where to file issues**: …
> Highlight the image maintainer and where to get help more explicitly

- zookeeper/content.md
Also update some links and do some cleanups.
> Document advanced Zookeeper configuration

- solr/content.md
- solr/license.md
- solr/maintainer.md
Changes since project is now maintained by Apache Solr project.
See https://github.com/docker-solr/docs/pull/1
> Update maintainer info for Solr

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.1.7)
> [nats-server] Release v2.1.7

- ghost/stack.yml
> Update Ghost example stack.yml to Ghost 3 (+ url env)

- arangodb/content.md
https://www.arangodb.com/docs/devel/programs-arangod-env-vars.html
> [ArangoDB] Add section about Limiting resource utilization

- mariadb/content.md
- mysql/content.md
Also make the boolean-like values more clear that a non-empty value is "true"
> Add missing MYSQL_INITDB_SKIP_TZINFO

- nextcloud/content.md
https://github.com/nextcloud/docker/pull/1131
> Drop DB prefix

- nextcloud/content.md
> Fix small typo

- silverpeas/content.md
Add an example of how to create a database and a user dedicated to that database with a PostgreSQL container.
> Refine the doc by adding an example

- znc/content.md
Addresses https://github.com/znc/znc-docker/issues/26
@felixsanz is this better?
> Try to make this less confusing

- golang/content.md
Closes https://github.com/docker-library/golang/issues/324
> Add a note about world-writeable "/go"

- postfixadmin/content.md
- postfixadmin/stack.yml
- postfixadmin/variant-apache.md
- postfixadmin/variant-fpm-alpine.md
- postfixadmin/variant-fpm.md
This contains some fixes suggested in https://github.com/docker-library/docs/pull/1147#pullrequestreview-194784423
> Update PostfixAdmin docs

- python/content.md
Closes https://github.com/docker-library/python/issues/486
> Add notice about /usr/bin/python

- drupal/variant-fpm.md
- wordpress/variant-fpm.md
https://github.com/docker-library/drupal/issues/159#issuecomment-659736738
> Symlink PHP FPM variant docs in drupal and wordpress

- friendica/content.md
Part of https://github.com/docker-library/official-images/pull/8420
> Friendica: Update SMTP environment settings

- wordpress/content.md
Closes https://github.com/docker-library/wordpress/issues/519
> Link to PHP docs for .ini configuration in WordPress

- redmine/content.md
Closes https://github.com/docker-library/redmine/issues/210
> Add Arbitrary User section to Redmine

- arangodb/content.md
- arangodb/license.md
> [ArangoDB] Minor adjustments to content.md

- registry/content.md
> registry: remove links to commercial support

- friendica/content.md
Part of https://github.com/docker-library/official-images/pull/8678
> Friendica - Add Docker Secrets

- sentry/deprecated.md
See docker-library/official-images#8673
> Add Sentry deprecation notice

- consul/content.md
URL is has changes without a redirection, this PR updates it to the current link
> Update URL to the doc

- bonita/content.md
PR relates to https://github.com/docker-library/official-images/pull/8822
> Update Bonita version to 7.11.2 & update migration download links

- docker/content.md
This is intended as an alternative approach to https://github.com/docker-library/docker/pull/258.
cc @thaJeztah @cpuguy83 @AkihiroSuda
> Add "Recommended Runtime Settings" to Docker description

- bonita/content.md
- bonita/stack.yml
Relates to https://github.com/docker-library/official-images/pull/9036
> chore(update): adapt documentation to latest Bonita version 7.11.3

- kong/content.md
(apologies for opening a new PR, but noticed this after #1832 got merged)
> kong: remove service mesh section

- ghost/stack.yml
A suggestion on how to start Ghost in development mode for theme development or similar tasks
> Start Ghost in development mode

- known/deprecated.md
See https://github.com/docker-library/official-images/pull/4670#issuecomment-629301112 and https://github.com/idno/Known-Docker/issues/13.
> Add "known" deprecation notice

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.21.0)
> [nats-streaming] Release v0.21.0

- neo4j/license.md
just a small change to the URL, hopefully it shouldn't be too troublesome.
Thanks!
/cc @akollegger
> Change to the Neo4j getting help link

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.2.0)
> [nats] Release v2.2.0

- plone/content.md
Refs https://github.com/plone/plone.docker/issues/155
> Plone 5.2.4 update docs

- maven/maintainer.md
cc @carlossg @michael-o
(https://github.com/carlossg/docker-maven/issues/202)
> Update Maven maintainer text

- friendica/content.md
- Fix Auto-Installer description
- Fix background task description
> Friendica: Fix description

- crate/README-short.txt
- crate/content.md
- crate/get-help.md
Specifically:
- Update wording to reflect the `crate/crate` `README.rst` file
- Adds some small copyedits
- Adds a link to the screenshot we use
> Update the CrateDB Docker image homepage

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.2.1)
> [nats] Release v2.2.1

- convertigo/README-short.txt
- convertigo/content.md
> Minor doc upgrade for the Convertigo 7.9.2 release

- archlinux/content.md
https://gitlab.archlinux.org/archlinux/archlinux-docker/-/merge_requests/57
> Reduce Arch Linux rootfs retention time to 2 months

- kibana/license.md
The current link gives you a 404 — sorry!
> Update the location of the Elastic License

- friendica/content.md
Doc PR for https://github.com/docker-library/official-images/pull/10040
> Friendica: Add SMTP_AUTH env

- telegraf/content.md
> fix broken Telegraf doc link

- bonita/content.md
Notably, anchors have all been named explicitely
> Update links to new version of Bonita documentation

- archlinux/content.md
Related Issue:
https://gitlab.archlinux.org/archlinux/archlinux-docker/-/issues/18
> Arch Linux: Add note on lsign-key

- nextcloud/content.md
I hope this makes sense. The current description sounds a bit confusing to me.
> Fix typo in Nextcloud Apache reverse-proxy docs

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.2.3)
> [nats] Release v2.2.3

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.2.4)
> [nats] Release v2.2.4

- almalinux/content.md
> AlmaLinux: fix typos in content.md

- dart/content.md
> dart: minor content fix

- fedora/README.md
- fedora/content.md
Git master was renamed to main.
> Fix broken Fedora links

- dart/github-repo
Fixes https://github.com/docker-library/docs/issues/1959
> Fix link for issues

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.2.5)
> [nats] Release v2.2.5

- kong/README.md
- kong/content.md
* [Bugfix] fix sample error for using kong with custom configuration
> fix sample error

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.2.6)
> [nats] Release v2.2.6

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.22.0)
> [nats-streaming] Release v0.22.0

- haskell/content.md
Closes the following issues:
- https://github.com/haskell/docker-haskell/issues/26
- https://github.com/haskell/docker-haskell/issues/27
cc @psftw
> Update haskell to make the example dockerfiles more stable

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.3.0)
> [nats] Release v2.3.0

- push.pl
Also, adjust `neo4j` to always defer the supported tag listing to GitHub.
Here's a examples of the rendered version for `openjdk` and `neo4j` (respectively):
---
**Note:** the description for this image is longer than the Hub length limit of 25000, so the "Supported tags" list has been trimmed to compensate.  See [docker/hub-beta-feedback#238](https://github.com/docker/hub-beta-feedback/issues/238) for more information.
- See ["Supported tags and respective `Dockerfile` links" at https://github.com/docker-library/docs/tree/master/openjdk/README.md](https://github.com/docker-library/docs/tree/master/openjdk/README.md#supported-tags-and-respective-dockerfile-links)
---
- See ["Supported tags and respective `Dockerfile` links" at https://github.com/docker-library/docs/tree/master/neo4j/README …
> Adjust "tag list too long" description to make the full link more obvious

- almalinux/content.md
Signed-off-by: Eugene Zamriy <eugene@zamriy.info>
> AlmaLinux: add information about minimal image

- php/variant-fpm.md
Closes https://github.com/docker-library/php/issues/1182
Closes https://github.com/docker-library/wordpress/issues/624
> Add a warning about the extreme insecurity of FPM exposed externally

- kaazing-gateway/README-short.txt
- kaazing-gateway/deprecated.md
(Not for lack of trying: https://github.com/docker-library/official-images/pull/4575#issuecomment-506198700 :disappointed:)
> Add deprecation notice for kaazing-gateway

- euleros/README-short.txt
- euleros/deprecated.md
https://github.com/docker-library/official-images/pull/5644#issuecomment-565200222 :disappointed:
> Add euleros deprecation notice

- nuxeo/README-short.txt
- nuxeo/deprecated.md
cc @dmetzler @aescaffre
https://github.com/docker-library/official-images/pull/6127#issuecomment-912530080
> Add Nuxeo deprecation notice

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.6.0)
> [nats] Release v2.6.0

- traefik/github-repo
- traefik/license.md
Fixes https://github.com/traefik/traefik-library-image/issues/13
> fix: use the new image repository

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.23.0)
> [nats-streaming] Release v0.23.0

- ubuntu/content.md
- ubuntu/maintainer.md
@mwhudson @toabctl this is a "straw man" to try to put more of this down in text form because _I_ can never seem to find it when I need it, so IMO it's useful data, but I'm very open to suggestions, alternative wordings, disgust, etc. :smile:
> Add more Ubuntu details

- varnish/content.md
explain how to reload the configuration on a live container
> [varnish] varnishreload info

- dart/content.md
@athomas can you please review?
> Clarify Dart getting started steps

- varnish/content.md
> Fix typo in the varnish docs

- nginx/content.md
Service is in life-support mode since quite some time.
> nginx: removed Amplify notices.

- friendica/content.md
> Friendica - fix typo

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.7.0)
> [nats] Release v2.7.0

- bonita/content.md
- bonita/get-help.md
- bonita/github-repo
- bonita/issues.md
as previous Github repo is now obsolete and archived
> Update Bonita community links

- nats-streaming/content.md
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.24.0)
> [nats-streaming] Release v0.24.0

- convertigo/content.md
- convertigo/license.md
> convertigo: change some keywords in description

- amazonlinux/content.md
Updates public wording for Amazon Linux 2022 Tech Preview.
> Update content.md to include public wording for AL 2022 Tech Preview

- mariadb/content.md
- mariadb/stack.yml
related to https://github.com/docker-library/official-images/pull/11864
> mariadb docs update for feb2022 release

- haskell/variant-slim.md
Based on https://github.com/docker-library/official-images/pull/11899 changes
> Haskell - add notes on slim variant

- ghost/stack.yml
Refs https://github.com/docker-library/ghost/issues/294
cc @daniellockyer :heart:
(I've tested and verified that this example works correctly and I'm able to connect to the UI after the migrations complete.)
> Update Ghost example to MySQL 8

- varnish/content.md
fix a few command lines while at it
> [varnish] add a few words about vmods

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.8.0)
> [nats] Release v2.8.0

- nextcloud/content.md
Backport recent changes in https://github.com/nextcloud/docker/blob/master/README.md
> Apply fixes from upstream

- jobber/README-short.txt
- jobber/deprecated.md
> Add "jobber" deprecation notice

- solr/README-short.txt
- solr/README.md
- solr/content.md
- solr/github-repo
- solr/issues.md
- solr/license.md
@janhoy
Note: Now that all "supported" images aren't affected by the CVEs, we might be able to take that down...
> Update docs for Solr 9.0

- mysql/stack.yml
Closes https://github.com/docker-library/mysql/issues/711
> Add a note about mysql_native_password next to our use of it

- phpmyadmin/content.md
- phpmyadmin/stack.yml
Ref: https://github.com/docker-library/official-images/pull/12931
> [phpmyadmin] Update documentation

- .template-helpers/generate-dockerfile-links-partial.tmpl
See https://github.com/docker-library/official-images/pull/13083 :eyes:
> Add support for Launchpad URLs

- nats/content.md
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.9.0)
> [nats] Release v2.9.0

- hello-world/content.md
- hello-world/update.sh
Fixes https://github.com/docker-library/hello-world/issues/104
> Add note that "hello-world" can run as an arbitrary user

- haproxy/content.md
see https://www.mail-archive.com/haproxy@formilux.org/msg42790.html
> Update the HAProxy Docs URL

- emqx/content.md
- emqx/get-help.md
Depends on https://github.com/docker-library/official-images/pull/13609
> update emqx docs

- convertigo/content.md
> Update for Convertigo 8.1.0 documentation: use PouchDB and configure SSL

- influxdb/README.md
- influxdb/content.md
> Update influxdb setup instructions

- .template-helpers/stack.md
We should eventually rename all the files too, but this is an easier start.
> Adjust "stack" note to prefer compose

- amazonlinux/content.md
- amazonlinux/issues.md
Updates to support AL2023 GA release
> Updates to support AL2023 GA release

- odoo/content.md
* adapt Odoo and Postgresql versions
* add a note about enterprise addons
* fix upgrade links
* remove wrong information about attachments storage
> Odoo: update documentation for the latest version

- unit/README-short.txt
- unit/content.md
- unit/get-help.md
Made description consistent with current style guide. Moved links to https.
Fixed key features link.
Fixed Community slack link.
> Unit: multiple fixes.

- php/content.md
The package has been renamed since bullseye.
> Update libfreetype package name

- python/content.md
See https://github.com/docker-library/python/issues/844 :eyes:
> Further clarify distro-provided Python

- convertigo/content.md
> Convertigo: Add new variables LOG_STDOUT and LOG_FILE

- registry/README-short.txt
Update the outdated short description for the registry DOI
> Change registry image short description

- registry/content.md
- registry/get-help.md
- registry/github-repo
- registry/license.md
- registry/maintainer.md
* updated links to official documentation
* updated symlink to community maintainers template
> update: registry docs

- geonetwork/content.md
- geonetwork/stack.yml
- geonetwork/variant-postgres.md
Update GeoNetwork documentation for version 4.
> Update documentation for GeoNetwork 4

- nextcloud/deprecated.md
As a follow-up to https://github.com/docker-library/docs/pull/2337
> update nextcloud wording

- postgres/content.md
- postgres/stack.yml
* added example for docker stack deploy (shared memory size)
* fix incorrect link
> postgres: update README.md

- mongo/content.md
More on docker-library/mongo#656.
> mongo: add more security information

- friendica/content.md
Part of https://github.com/docker-library/official-images/pull/16343
> [Friendica] Fix `tls_starttls` setting

- varnish/content.md
new 7.5 release introduce new variables to configure `varnish`
> varnish: introduce new env variables

- kong/license.md
fixes https://github.com/Kong/kong/issues/13322
> update kong license link

- push.pl
It turns out that the Hub description length limit is 25k *bytes*, not characters (contrary to https://github.com/docker/hub-feedback/issues/238 and https://github.com/docker/roadmap/issues/475).  We've gotten lucky that our few unicode glyphs have landed so far such that we've never run into a problem with this before now, but we're currently hitting this while trying to push the `amd64/nextcloud` description in that the trimmed version ends up being exactly 25,003 bytes thanks to the unicode glyphs throwing off our trimming calculations (and getting really [un]lucky with the exact positioning of the markdown such that our trimming doesn't walk back far enough).
This fixes that by calculating and trimming based on bytes, accounting for cases of unicode glyphs directly spanning the 25k …
> Trim descriptions based on bytes, not characters

- bonita/content.md
- bonita/stack.yml
Related to https://github.com/docker-library/official-images/pull/17714
> update Bonita Platform and Update Tool versions

- sonarqube/content.md
Hello team!
I need to update the description of our SonarQube Community Build.
Please let me know if I'm missing anything in this PR.
> Update SonarQube Community Build description

- clickhouse/content.md
It was removed during the initial PR #2397
> Add versions description

- golang/content.md
> Remove unnecessary "go mod verify"

- adminer/README-short.txt
- adminer/deprecated.md
- adminer/license.md
The project is now actively maintained.
> Remove deprecation notice

- mysql/content.md
- percona/content.md
See: https://github.com/docker-library/mysql/commit/24e6931ec8187930dfad5ef2d205a9874f86ca4c
> docs: Update MySQL/Percona random root password generator

- emqx/README-short.txt
(this is a consistency follow-up to #2571)
> Add "DEPRECATED" to short description for emqx

- ghost/README.md
- ghost/content.md
Remove obsolete parenthesis, probably a markdown leftover
> Remove obsolete parenthesis

- notary/README-short.txt
- notary/deprecated.md
See also https://github.com/notaryproject/.github/issues/70
> Deprecate the Notary image
